# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from nlp.v1 import nlp_pb2 as nlp_dot_v1_dot_nlp__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nlp/v1/nlp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NLPServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeDanmaku = channel.unary_unary(
                '/nlp.v1.NLPService/AnalyzeDanmaku',
                request_serializer=nlp_dot_v1_dot_nlp__pb2.AnalyzeDanmakuRequest.SerializeToString,
                response_deserializer=nlp_dot_v1_dot_nlp__pb2.AnalyzeDanmakuResponse.FromString,
                _registered_method=True)
        self.BatchAnalyzeDanmaku = channel.unary_unary(
                '/nlp.v1.NLPService/BatchAnalyzeDanmaku',
                request_serializer=nlp_dot_v1_dot_nlp__pb2.BatchAnalyzeDanmakuRequest.SerializeToString,
                response_deserializer=nlp_dot_v1_dot_nlp__pb2.BatchAnalyzeDanmakuResponse.FromString,
                _registered_method=True)
        self.CheckSensitive = channel.unary_unary(
                '/nlp.v1.NLPService/CheckSensitive',
                request_serializer=nlp_dot_v1_dot_nlp__pb2.CheckSensitiveRequest.SerializeToString,
                response_deserializer=nlp_dot_v1_dot_nlp__pb2.CheckSensitiveResponse.FromString,
                _registered_method=True)
        self.ExtractEntities = channel.unary_unary(
                '/nlp.v1.NLPService/ExtractEntities',
                request_serializer=nlp_dot_v1_dot_nlp__pb2.ExtractEntitiesRequest.SerializeToString,
                response_deserializer=nlp_dot_v1_dot_nlp__pb2.ExtractEntitiesResponse.FromString,
                _registered_method=True)
        self.RewriteText = channel.unary_unary(
                '/nlp.v1.NLPService/RewriteText',
                request_serializer=nlp_dot_v1_dot_nlp__pb2.RewriteTextRequest.SerializeToString,
                response_deserializer=nlp_dot_v1_dot_nlp__pb2.RewriteTextResponse.FromString,
                _registered_method=True)


class NLPServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AnalyzeDanmaku(self, request, context):
        """── Danmaku Analysis ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchAnalyzeDanmaku(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckSensitive(self, request, context):
        """── Sensitive Word Detection ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractEntities(self, request, context):
        """── Text Processing ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RewriteText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLPServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeDanmaku': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeDanmaku,
                    request_deserializer=nlp_dot_v1_dot_nlp__pb2.AnalyzeDanmakuRequest.FromString,
                    response_serializer=nlp_dot_v1_dot_nlp__pb2.AnalyzeDanmakuResponse.SerializeToString,
            ),
            'BatchAnalyzeDanmaku': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchAnalyzeDanmaku,
                    request_deserializer=nlp_dot_v1_dot_nlp__pb2.BatchAnalyzeDanmakuRequest.FromString,
                    response_serializer=nlp_dot_v1_dot_nlp__pb2.BatchAnalyzeDanmakuResponse.SerializeToString,
            ),
            'CheckSensitive': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckSensitive,
                    request_deserializer=nlp_dot_v1_dot_nlp__pb2.CheckSensitiveRequest.FromString,
                    response_serializer=nlp_dot_v1_dot_nlp__pb2.CheckSensitiveResponse.SerializeToString,
            ),
            'ExtractEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEntities,
                    request_deserializer=nlp_dot_v1_dot_nlp__pb2.ExtractEntitiesRequest.FromString,
                    response_serializer=nlp_dot_v1_dot_nlp__pb2.ExtractEntitiesResponse.SerializeToString,
            ),
            'RewriteText': grpc.unary_unary_rpc_method_handler(
                    servicer.RewriteText,
                    request_deserializer=nlp_dot_v1_dot_nlp__pb2.RewriteTextRequest.FromString,
                    response_serializer=nlp_dot_v1_dot_nlp__pb2.RewriteTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nlp.v1.NLPService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('nlp.v1.NLPService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NLPService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeDanmaku(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp.v1.NLPService/AnalyzeDanmaku',
            nlp_dot_v1_dot_nlp__pb2.AnalyzeDanmakuRequest.SerializeToString,
            nlp_dot_v1_dot_nlp__pb2.AnalyzeDanmakuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchAnalyzeDanmaku(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp.v1.NLPService/BatchAnalyzeDanmaku',
            nlp_dot_v1_dot_nlp__pb2.BatchAnalyzeDanmakuRequest.SerializeToString,
            nlp_dot_v1_dot_nlp__pb2.BatchAnalyzeDanmakuResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckSensitive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp.v1.NLPService/CheckSensitive',
            nlp_dot_v1_dot_nlp__pb2.CheckSensitiveRequest.SerializeToString,
            nlp_dot_v1_dot_nlp__pb2.CheckSensitiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp.v1.NLPService/ExtractEntities',
            nlp_dot_v1_dot_nlp__pb2.ExtractEntitiesRequest.SerializeToString,
            nlp_dot_v1_dot_nlp__pb2.ExtractEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RewriteText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/nlp.v1.NLPService/RewriteText',
            nlp_dot_v1_dot_nlp__pb2.RewriteTextRequest.SerializeToString,
            nlp_dot_v1_dot_nlp__pb2.RewriteTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
