# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from user.v1 import user_pb2 as user_dot_v1_dot_user__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in user/v1/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/user.v1.UserService/Register',
                request_serializer=user_dot_v1_dot_user__pb2.RegisterRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/user.v1.UserService/Login',
                request_serializer=user_dot_v1_dot_user__pb2.LoginRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/user.v1.UserService/RefreshToken',
                request_serializer=user_dot_v1_dot_user__pb2.RefreshRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.AuthResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/user.v1.UserService/Logout',
                request_serializer=user_dot_v1_dot_user__pb2.LogoutRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Error.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/user.v1.UserService/GetUser',
                request_serializer=user_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/user.v1.UserService/UpdateUser',
                request_serializer=user_dot_v1_dot_user__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.User.FromString,
                _registered_method=True)
        self.ListUsers = channel.unary_unary(
                '/user.v1.UserService/ListUsers',
                request_serializer=user_dot_v1_dot_user__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.CheckPermission = channel.unary_unary(
                '/user.v1.UserService/CheckPermission',
                request_serializer=user_dot_v1_dot_user__pb2.CheckPermissionRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.CheckPermissionResponse.FromString,
                _registered_method=True)
        self.AssignRole = channel.unary_unary(
                '/user.v1.UserService/AssignRole',
                request_serializer=user_dot_v1_dot_user__pb2.AssignRoleRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.User.FromString,
                _registered_method=True)
        self.ListStores = channel.unary_unary(
                '/user.v1.UserService/ListStores',
                request_serializer=user_dot_v1_dot_user__pb2.ListStoresRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.ListStoresResponse.FromString,
                _registered_method=True)
        self.SwitchStore = channel.unary_unary(
                '/user.v1.UserService/SwitchStore',
                request_serializer=user_dot_v1_dot_user__pb2.SwitchStoreRequest.SerializeToString,
                response_deserializer=user_dot_v1_dot_user__pb2.Store.FromString,
                _registered_method=True)


class UserServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """── Auth ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Empty on success → null
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """── User CRUD ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckPermission(self, request, context):
        """── Permission ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStores(self, request, context):
        """── Store ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchStore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=user_dot_v1_dot_user__pb2.RegisterRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.AuthResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=user_dot_v1_dot_user__pb2.LoginRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.AuthResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=user_dot_v1_dot_user__pb2.RefreshRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.AuthResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=user_dot_v1_dot_user__pb2.LogoutRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Error.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=user_dot_v1_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=user_dot_v1_dot_user__pb2.UpdateUserRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.User.SerializeToString,
            ),
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=user_dot_v1_dot_user__pb2.ListUsersRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.ListUsersResponse.SerializeToString,
            ),
            'CheckPermission': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckPermission,
                    request_deserializer=user_dot_v1_dot_user__pb2.CheckPermissionRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.CheckPermissionResponse.SerializeToString,
            ),
            'AssignRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRole,
                    request_deserializer=user_dot_v1_dot_user__pb2.AssignRoleRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.User.SerializeToString,
            ),
            'ListStores': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStores,
                    request_deserializer=user_dot_v1_dot_user__pb2.ListStoresRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.ListStoresResponse.SerializeToString,
            ),
            'SwitchStore': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchStore,
                    request_deserializer=user_dot_v1_dot_user__pb2.SwitchStoreRequest.FromString,
                    response_serializer=user_dot_v1_dot_user__pb2.Store.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'user.v1.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('user.v1.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/Register',
            user_dot_v1_dot_user__pb2.RegisterRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/Login',
            user_dot_v1_dot_user__pb2.LoginRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/RefreshToken',
            user_dot_v1_dot_user__pb2.RefreshRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.AuthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/Logout',
            user_dot_v1_dot_user__pb2.LogoutRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/GetUser',
            user_dot_v1_dot_user__pb2.GetUserRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/UpdateUser',
            user_dot_v1_dot_user__pb2.UpdateUserRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/ListUsers',
            user_dot_v1_dot_user__pb2.ListUsersRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/CheckPermission',
            user_dot_v1_dot_user__pb2.CheckPermissionRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.CheckPermissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/AssignRole',
            user_dot_v1_dot_user__pb2.AssignRoleRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/ListStores',
            user_dot_v1_dot_user__pb2.ListStoresRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.ListStoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchStore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/user.v1.UserService/SwitchStore',
            user_dot_v1_dot_user__pb2.SwitchStoreRequest.SerializeToString,
            user_dot_v1_dot_user__pb2.Store.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
