apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: livestream-tts
  labels:
    app: user-svc
spec:
  type: ClusterIP
  selector:
    app: user-svc
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
