# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from avatar.v1 import avatar_pb2 as avatar_dot_v1_dot_avatar__pb2
from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in avatar/v1/avatar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AvatarServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAvatar = channel.unary_unary(
                '/avatar.v1.AvatarService/CreateAvatar',
                request_serializer=avatar_dot_v1_dot_avatar__pb2.CreateAvatarRequest.SerializeToString,
                response_deserializer=avatar_dot_v1_dot_avatar__pb2.Avatar.FromString,
                _registered_method=True)
        self.GetAvatar = channel.unary_unary(
                '/avatar.v1.AvatarService/GetAvatar',
                request_serializer=avatar_dot_v1_dot_avatar__pb2.GetAvatarRequest.SerializeToString,
                response_deserializer=avatar_dot_v1_dot_avatar__pb2.Avatar.FromString,
                _registered_method=True)
        self.UpdateAvatar = channel.unary_unary(
                '/avatar.v1.AvatarService/UpdateAvatar',
                request_serializer=avatar_dot_v1_dot_avatar__pb2.UpdateAvatarRequest.SerializeToString,
                response_deserializer=avatar_dot_v1_dot_avatar__pb2.Avatar.FromString,
                _registered_method=True)
        self.DeleteAvatar = channel.unary_unary(
                '/avatar.v1.AvatarService/DeleteAvatar',
                request_serializer=avatar_dot_v1_dot_avatar__pb2.DeleteAvatarRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Error.FromString,
                _registered_method=True)
        self.ListAvatars = channel.unary_unary(
                '/avatar.v1.AvatarService/ListAvatars',
                request_serializer=avatar_dot_v1_dot_avatar__pb2.ListAvatarsRequest.SerializeToString,
                response_deserializer=avatar_dot_v1_dot_avatar__pb2.ListAvatarsResponse.FromString,
                _registered_method=True)
        self.StartClone = channel.unary_unary(
                '/avatar.v1.AvatarService/StartClone',
                request_serializer=avatar_dot_v1_dot_avatar__pb2.StartCloneRequest.SerializeToString,
                response_deserializer=avatar_dot_v1_dot_avatar__pb2.CloneTask.FromString,
                _registered_method=True)
        self.GetCloneTask = channel.unary_unary(
                '/avatar.v1.AvatarService/GetCloneTask',
                request_serializer=avatar_dot_v1_dot_avatar__pb2.GetCloneTaskRequest.SerializeToString,
                response_deserializer=avatar_dot_v1_dot_avatar__pb2.CloneTask.FromString,
                _registered_method=True)


class AvatarServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateAvatar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAvatar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAvatar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteAvatar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAvatars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartClone(self, request, context):
        """Clone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCloneTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AvatarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAvatar,
                    request_deserializer=avatar_dot_v1_dot_avatar__pb2.CreateAvatarRequest.FromString,
                    response_serializer=avatar_dot_v1_dot_avatar__pb2.Avatar.SerializeToString,
            ),
            'GetAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAvatar,
                    request_deserializer=avatar_dot_v1_dot_avatar__pb2.GetAvatarRequest.FromString,
                    response_serializer=avatar_dot_v1_dot_avatar__pb2.Avatar.SerializeToString,
            ),
            'UpdateAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAvatar,
                    request_deserializer=avatar_dot_v1_dot_avatar__pb2.UpdateAvatarRequest.FromString,
                    response_serializer=avatar_dot_v1_dot_avatar__pb2.Avatar.SerializeToString,
            ),
            'DeleteAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteAvatar,
                    request_deserializer=avatar_dot_v1_dot_avatar__pb2.DeleteAvatarRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Error.SerializeToString,
            ),
            'ListAvatars': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAvatars,
                    request_deserializer=avatar_dot_v1_dot_avatar__pb2.ListAvatarsRequest.FromString,
                    response_serializer=avatar_dot_v1_dot_avatar__pb2.ListAvatarsResponse.SerializeToString,
            ),
            'StartClone': grpc.unary_unary_rpc_method_handler(
                    servicer.StartClone,
                    request_deserializer=avatar_dot_v1_dot_avatar__pb2.StartCloneRequest.FromString,
                    response_serializer=avatar_dot_v1_dot_avatar__pb2.CloneTask.SerializeToString,
            ),
            'GetCloneTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCloneTask,
                    request_deserializer=avatar_dot_v1_dot_avatar__pb2.GetCloneTaskRequest.FromString,
                    response_serializer=avatar_dot_v1_dot_avatar__pb2.CloneTask.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'avatar.v1.AvatarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('avatar.v1.AvatarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AvatarService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avatar.v1.AvatarService/CreateAvatar',
            avatar_dot_v1_dot_avatar__pb2.CreateAvatarRequest.SerializeToString,
            avatar_dot_v1_dot_avatar__pb2.Avatar.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avatar.v1.AvatarService/GetAvatar',
            avatar_dot_v1_dot_avatar__pb2.GetAvatarRequest.SerializeToString,
            avatar_dot_v1_dot_avatar__pb2.Avatar.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avatar.v1.AvatarService/UpdateAvatar',
            avatar_dot_v1_dot_avatar__pb2.UpdateAvatarRequest.SerializeToString,
            avatar_dot_v1_dot_avatar__pb2.Avatar.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avatar.v1.AvatarService/DeleteAvatar',
            avatar_dot_v1_dot_avatar__pb2.DeleteAvatarRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAvatars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avatar.v1.AvatarService/ListAvatars',
            avatar_dot_v1_dot_avatar__pb2.ListAvatarsRequest.SerializeToString,
            avatar_dot_v1_dot_avatar__pb2.ListAvatarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartClone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avatar.v1.AvatarService/StartClone',
            avatar_dot_v1_dot_avatar__pb2.StartCloneRequest.SerializeToString,
            avatar_dot_v1_dot_avatar__pb2.CloneTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCloneTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avatar.v1.AvatarService/GetCloneTask',
            avatar_dot_v1_dot_avatar__pb2.GetCloneTaskRequest.SerializeToString,
            avatar_dot_v1_dot_avatar__pb2.CloneTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
