"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Shared message types used across all services.
Import this in every service proto file.
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Pagination(_message.Message):
    """── Pagination ──"""

    DESCRIPTOR: _descriptor.Descriptor

    PAGE_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    page: _builtins.int
    """1-indexed"""
    page_size: _builtins.int
    """default: 20, max: 100"""
    def __init__(
        self,
        *,
        page: _builtins.int = ...,
        page_size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page", b"page", "page_size", b"page_size"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Pagination: _TypeAlias = Pagination  # noqa: Y015

@_typing.final
class PageInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAGE_FIELD_NUMBER: _builtins.int
    PAGE_SIZE_FIELD_NUMBER: _builtins.int
    TOTAL_COUNT_FIELD_NUMBER: _builtins.int
    TOTAL_PAGES_FIELD_NUMBER: _builtins.int
    page: _builtins.int
    page_size: _builtins.int
    total_count: _builtins.int
    total_pages: _builtins.int
    def __init__(
        self,
        *,
        page: _builtins.int = ...,
        page_size: _builtins.int = ...,
        total_count: _builtins.int = ...,
        total_pages: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page", b"page", "page_size", b"page_size", "total_count", b"total_count", "total_pages", b"total_pages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PageInfo: _TypeAlias = PageInfo  # noqa: Y015

@_typing.final
class Error(_message.Message):
    """── Standard error ──"""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DetailsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    DETAILS_FIELD_NUMBER: _builtins.int
    code: _builtins.int
    """Full error code (domain * 1000 + code)"""
    message: _builtins.str
    @_builtins.property
    def details(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        code: _builtins.int = ...,
        message: _builtins.str = ...,
        details: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "details", b"details", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Error: _TypeAlias = Error  # noqa: Y015

@_typing.final
class Timestamps(_message.Message):
    """── Common fields ──"""

    DESCRIPTOR: _descriptor.Descriptor

    CREATED_AT_FIELD_NUMBER: _builtins.int
    UPDATED_AT_FIELD_NUMBER: _builtins.int
    created_at: _builtins.int
    """Unix milliseconds"""
    updated_at: _builtins.int
    """Unix milliseconds"""
    def __init__(
        self,
        *,
        created_at: _builtins.int = ...,
        updated_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "updated_at", b"updated_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Timestamps: _TypeAlias = Timestamps  # noqa: Y015

@_typing.final
class AuditInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CREATED_BY_FIELD_NUMBER: _builtins.int
    UPDATED_BY_FIELD_NUMBER: _builtins.int
    TIMESTAMPS_FIELD_NUMBER: _builtins.int
    created_by: _builtins.str
    updated_by: _builtins.str
    @_builtins.property
    def timestamps(self) -> Global___Timestamps: ...
    def __init__(
        self,
        *,
        created_by: _builtins.str = ...,
        updated_by: _builtins.str = ...,
        timestamps: Global___Timestamps | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamps", b"timestamps"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_by", b"created_by", "timestamps", b"timestamps", "updated_by", b"updated_by"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuditInfo: _TypeAlias = AuditInfo  # noqa: Y015

@_typing.final
class Address(_message.Message):
    """── Address / Contact ──"""

    DESCRIPTOR: _descriptor.Descriptor

    COUNTRY_FIELD_NUMBER: _builtins.int
    PROVINCE_FIELD_NUMBER: _builtins.int
    CITY_FIELD_NUMBER: _builtins.int
    DISTRICT_FIELD_NUMBER: _builtins.int
    LINE1_FIELD_NUMBER: _builtins.int
    LINE2_FIELD_NUMBER: _builtins.int
    POSTAL_CODE_FIELD_NUMBER: _builtins.int
    country: _builtins.str
    province: _builtins.str
    city: _builtins.str
    district: _builtins.str
    line1: _builtins.str
    line2: _builtins.str
    postal_code: _builtins.str
    def __init__(
        self,
        *,
        country: _builtins.str = ...,
        province: _builtins.str = ...,
        city: _builtins.str = ...,
        district: _builtins.str = ...,
        line1: _builtins.str = ...,
        line2: _builtins.str = ...,
        postal_code: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["city", b"city", "country", b"country", "district", b"district", "line1", b"line1", "line2", b"line2", "postal_code", b"postal_code", "province", b"province"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Address: _TypeAlias = Address  # noqa: Y015

@_typing.final
class Money(_message.Message):
    """── Money ──"""

    DESCRIPTOR: _descriptor.Descriptor

    AMOUNT_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    amount: _builtins.int
    """In smallest unit (e.g., fen for CNY)"""
    currency: _builtins.str
    """CNY, USD, etc."""
    def __init__(
        self,
        *,
        amount: _builtins.int = ...,
        currency: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "currency", b"currency"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Money: _TypeAlias = Money  # noqa: Y015
