"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Billing Service — Subscription Plans, Usage Metering, Invoices, Payment"""

from collections import abc as _abc
from common.v1 import common_pb2 as _common_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _SubscriptionStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SubscriptionStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SubscriptionStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SUBSCRIPTION_STATUS_UNSPECIFIED: _SubscriptionStatus.ValueType  # 0
    SUBSCRIPTION_STATUS_ACTIVE: _SubscriptionStatus.ValueType  # 1
    SUBSCRIPTION_STATUS_EXPIRED: _SubscriptionStatus.ValueType  # 2
    SUBSCRIPTION_STATUS_CANCELLED: _SubscriptionStatus.ValueType  # 3

class SubscriptionStatus(_SubscriptionStatus, metaclass=_SubscriptionStatusEnumTypeWrapper): ...

SUBSCRIPTION_STATUS_UNSPECIFIED: SubscriptionStatus.ValueType  # 0
SUBSCRIPTION_STATUS_ACTIVE: SubscriptionStatus.ValueType  # 1
SUBSCRIPTION_STATUS_EXPIRED: SubscriptionStatus.ValueType  # 2
SUBSCRIPTION_STATUS_CANCELLED: SubscriptionStatus.ValueType  # 3
Global___SubscriptionStatus: _TypeAlias = SubscriptionStatus  # noqa: Y015

class _InvoiceStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _InvoiceStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_InvoiceStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    INVOICE_STATUS_UNSPECIFIED: _InvoiceStatus.ValueType  # 0
    INVOICE_STATUS_PENDING: _InvoiceStatus.ValueType  # 1
    INVOICE_STATUS_PAID: _InvoiceStatus.ValueType  # 2
    INVOICE_STATUS_OVERDUE: _InvoiceStatus.ValueType  # 3

class InvoiceStatus(_InvoiceStatus, metaclass=_InvoiceStatusEnumTypeWrapper): ...

INVOICE_STATUS_UNSPECIFIED: InvoiceStatus.ValueType  # 0
INVOICE_STATUS_PENDING: InvoiceStatus.ValueType  # 1
INVOICE_STATUS_PAID: InvoiceStatus.ValueType  # 2
INVOICE_STATUS_OVERDUE: InvoiceStatus.ValueType  # 3
Global___InvoiceStatus: _TypeAlias = InvoiceStatus  # noqa: Y015

class _PaymentMethod:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PaymentMethodEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PaymentMethod.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PAYMENT_METHOD_UNSPECIFIED: _PaymentMethod.ValueType  # 0
    PAYMENT_METHOD_WECHAT: _PaymentMethod.ValueType  # 1
    PAYMENT_METHOD_ALIPAY: _PaymentMethod.ValueType  # 2

class PaymentMethod(_PaymentMethod, metaclass=_PaymentMethodEnumTypeWrapper): ...

PAYMENT_METHOD_UNSPECIFIED: PaymentMethod.ValueType  # 0
PAYMENT_METHOD_WECHAT: PaymentMethod.ValueType  # 1
PAYMENT_METHOD_ALIPAY: PaymentMethod.ValueType  # 2
Global___PaymentMethod: _TypeAlias = PaymentMethod  # noqa: Y015

class _PaymentStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PaymentStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PaymentStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PAYMENT_STATUS_UNSPECIFIED: _PaymentStatus.ValueType  # 0
    PAYMENT_STATUS_PENDING: _PaymentStatus.ValueType  # 1
    PAYMENT_STATUS_SUCCESS: _PaymentStatus.ValueType  # 2
    PAYMENT_STATUS_FAILED: _PaymentStatus.ValueType  # 3

class PaymentStatus(_PaymentStatus, metaclass=_PaymentStatusEnumTypeWrapper): ...

PAYMENT_STATUS_UNSPECIFIED: PaymentStatus.ValueType  # 0
PAYMENT_STATUS_PENDING: PaymentStatus.ValueType  # 1
PAYMENT_STATUS_SUCCESS: PaymentStatus.ValueType  # 2
PAYMENT_STATUS_FAILED: PaymentStatus.ValueType  # 3
Global___PaymentStatus: _TypeAlias = PaymentStatus  # noqa: Y015

class _UsageMetric:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _UsageMetricEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_UsageMetric.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    USAGE_METRIC_UNSPECIFIED: _UsageMetric.ValueType  # 0
    USAGE_METRIC_STREAMING_SECONDS: _UsageMetric.ValueType  # 1
    USAGE_METRIC_API_CALLS: _UsageMetric.ValueType  # 2
    USAGE_METRIC_LLM_TOKENS: _UsageMetric.ValueType  # 3

class UsageMetric(_UsageMetric, metaclass=_UsageMetricEnumTypeWrapper): ...

USAGE_METRIC_UNSPECIFIED: UsageMetric.ValueType  # 0
USAGE_METRIC_STREAMING_SECONDS: UsageMetric.ValueType  # 1
USAGE_METRIC_API_CALLS: UsageMetric.ValueType  # 2
USAGE_METRIC_LLM_TOKENS: UsageMetric.ValueType  # 3
Global___UsageMetric: _TypeAlias = UsageMetric  # noqa: Y015

@_typing.final
class Plan(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PLAN_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    MONTHLY_PRICE_FIELD_NUMBER: _builtins.int
    QUOTA_FIELD_NUMBER: _builtins.int
    IS_ACTIVE_FIELD_NUMBER: _builtins.int
    plan_id: _builtins.str
    name: _builtins.str
    description: _builtins.str
    is_active: _builtins.bool
    @_builtins.property
    def monthly_price(self) -> _common_pb2.Money: ...
    @_builtins.property
    def quota(self) -> Global___PlanQuota: ...
    def __init__(
        self,
        *,
        plan_id: _builtins.str = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        monthly_price: _common_pb2.Money | None = ...,
        quota: Global___PlanQuota | None = ...,
        is_active: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["monthly_price", b"monthly_price", "quota", b"quota"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "is_active", b"is_active", "monthly_price", b"monthly_price", "name", b"name", "plan_id", b"plan_id", "quota", b"quota"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Plan: _TypeAlias = Plan  # noqa: Y015

@_typing.final
class PlanQuota(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAX_LIVE_ROOMS_FIELD_NUMBER: _builtins.int
    MAX_CONCURRENT_STREAMS_FIELD_NUMBER: _builtins.int
    MAX_PRODUCTS_FIELD_NUMBER: _builtins.int
    MAX_AVATARS_FIELD_NUMBER: _builtins.int
    MAX_VOICES_FIELD_NUMBER: _builtins.int
    STREAMING_HOURS_PER_MONTH_FIELD_NUMBER: _builtins.int
    INCLUDES_API_ACCESS_FIELD_NUMBER: _builtins.int
    max_live_rooms: _builtins.int
    max_concurrent_streams: _builtins.int
    max_products: _builtins.int
    max_avatars: _builtins.int
    max_voices: _builtins.int
    streaming_hours_per_month: _builtins.int
    includes_api_access: _builtins.bool
    def __init__(
        self,
        *,
        max_live_rooms: _builtins.int = ...,
        max_concurrent_streams: _builtins.int = ...,
        max_products: _builtins.int = ...,
        max_avatars: _builtins.int = ...,
        max_voices: _builtins.int = ...,
        streaming_hours_per_month: _builtins.int = ...,
        includes_api_access: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["includes_api_access", b"includes_api_access", "max_avatars", b"max_avatars", "max_concurrent_streams", b"max_concurrent_streams", "max_live_rooms", b"max_live_rooms", "max_products", b"max_products", "max_voices", b"max_voices", "streaming_hours_per_month", b"streaming_hours_per_month"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlanQuota: _TypeAlias = PlanQuota  # noqa: Y015

@_typing.final
class Subscription(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUBSCRIPTION_ID_FIELD_NUMBER: _builtins.int
    STORE_ID_FIELD_NUMBER: _builtins.int
    PLAN_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    STARTED_AT_FIELD_NUMBER: _builtins.int
    EXPIRES_AT_FIELD_NUMBER: _builtins.int
    AUTO_RENEW_FIELD_NUMBER: _builtins.int
    subscription_id: _builtins.str
    store_id: _builtins.str
    plan_id: _builtins.str
    status: Global___SubscriptionStatus.ValueType
    started_at: _builtins.int
    expires_at: _builtins.int
    auto_renew: _builtins.bool
    def __init__(
        self,
        *,
        subscription_id: _builtins.str = ...,
        store_id: _builtins.str = ...,
        plan_id: _builtins.str = ...,
        status: Global___SubscriptionStatus.ValueType = ...,
        started_at: _builtins.int = ...,
        expires_at: _builtins.int = ...,
        auto_renew: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auto_renew", b"auto_renew", "expires_at", b"expires_at", "plan_id", b"plan_id", "started_at", b"started_at", "status", b"status", "store_id", b"store_id", "subscription_id", b"subscription_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Subscription: _TypeAlias = Subscription  # noqa: Y015

@_typing.final
class Usage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    BILLING_PERIOD_FIELD_NUMBER: _builtins.int
    STREAMING_MINUTES_USED_FIELD_NUMBER: _builtins.int
    STREAMING_MINUTES_LIMIT_FIELD_NUMBER: _builtins.int
    PRODUCTS_USED_FIELD_NUMBER: _builtins.int
    PRODUCTS_LIMIT_FIELD_NUMBER: _builtins.int
    API_CALLS_USED_FIELD_NUMBER: _builtins.int
    LLM_TOKENS_USED_FIELD_NUMBER: _builtins.int
    ESTIMATED_COST_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    billing_period: _builtins.str
    streaming_minutes_used: _builtins.int
    streaming_minutes_limit: _builtins.int
    products_used: _builtins.int
    products_limit: _builtins.int
    api_calls_used: _builtins.int
    llm_tokens_used: _builtins.int
    @_builtins.property
    def estimated_cost(self) -> _common_pb2.Money: ...
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        billing_period: _builtins.str = ...,
        streaming_minutes_used: _builtins.int = ...,
        streaming_minutes_limit: _builtins.int = ...,
        products_used: _builtins.int = ...,
        products_limit: _builtins.int = ...,
        api_calls_used: _builtins.int = ...,
        llm_tokens_used: _builtins.int = ...,
        estimated_cost: _common_pb2.Money | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["estimated_cost", b"estimated_cost"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["api_calls_used", b"api_calls_used", "billing_period", b"billing_period", "estimated_cost", b"estimated_cost", "llm_tokens_used", b"llm_tokens_used", "products_limit", b"products_limit", "products_used", b"products_used", "store_id", b"store_id", "streaming_minutes_limit", b"streaming_minutes_limit", "streaming_minutes_used", b"streaming_minutes_used"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Usage: _TypeAlias = Usage  # noqa: Y015

@_typing.final
class Invoice(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INVOICE_ID_FIELD_NUMBER: _builtins.int
    STORE_ID_FIELD_NUMBER: _builtins.int
    BILLING_PERIOD_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    PDF_URL_FIELD_NUMBER: _builtins.int
    ISSUED_AT_FIELD_NUMBER: _builtins.int
    PAID_AT_FIELD_NUMBER: _builtins.int
    invoice_id: _builtins.str
    store_id: _builtins.str
    billing_period: _builtins.str
    status: Global___InvoiceStatus.ValueType
    pdf_url: _builtins.str
    issued_at: _builtins.int
    paid_at: _builtins.int
    @_builtins.property
    def amount(self) -> _common_pb2.Money: ...
    def __init__(
        self,
        *,
        invoice_id: _builtins.str = ...,
        store_id: _builtins.str = ...,
        billing_period: _builtins.str = ...,
        amount: _common_pb2.Money | None = ...,
        status: Global___InvoiceStatus.ValueType = ...,
        pdf_url: _builtins.str = ...,
        issued_at: _builtins.int = ...,
        paid_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "billing_period", b"billing_period", "invoice_id", b"invoice_id", "issued_at", b"issued_at", "paid_at", b"paid_at", "pdf_url", b"pdf_url", "status", b"status", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Invoice: _TypeAlias = Invoice  # noqa: Y015

@_typing.final
class Payment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAYMENT_ID_FIELD_NUMBER: _builtins.int
    INVOICE_ID_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    AMOUNT_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    QR_CODE_URL_FIELD_NUMBER: _builtins.int
    PAYMENT_URL_FIELD_NUMBER: _builtins.int
    payment_id: _builtins.str
    invoice_id: _builtins.str
    method: Global___PaymentMethod.ValueType
    status: Global___PaymentStatus.ValueType
    qr_code_url: _builtins.str
    payment_url: _builtins.str
    @_builtins.property
    def amount(self) -> _common_pb2.Money: ...
    def __init__(
        self,
        *,
        payment_id: _builtins.str = ...,
        invoice_id: _builtins.str = ...,
        method: Global___PaymentMethod.ValueType = ...,
        amount: _common_pb2.Money | None = ...,
        status: Global___PaymentStatus.ValueType = ...,
        qr_code_url: _builtins.str = ...,
        payment_url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["amount", b"amount", "invoice_id", b"invoice_id", "method", b"method", "payment_id", b"payment_id", "payment_url", b"payment_url", "qr_code_url", b"qr_code_url", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Payment: _TypeAlias = Payment  # noqa: Y015

@_typing.final
class ListPlansRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListPlansRequest: _TypeAlias = ListPlansRequest  # noqa: Y015

@_typing.final
class ListPlansResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PLANS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def plans(self) -> _containers.RepeatedCompositeFieldContainer[Global___Plan]: ...
    def __init__(
        self,
        *,
        plans: _abc.Iterable[Global___Plan] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["plans", b"plans"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListPlansResponse: _TypeAlias = ListPlansResponse  # noqa: Y015

@_typing.final
class SubscribeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    PLAN_ID_FIELD_NUMBER: _builtins.int
    AUTO_RENEW_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    plan_id: _builtins.str
    auto_renew: _builtins.bool
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        plan_id: _builtins.str = ...,
        auto_renew: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auto_renew", b"auto_renew", "plan_id", b"plan_id", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubscribeRequest: _TypeAlias = SubscribeRequest  # noqa: Y015

@_typing.final
class ReportUsageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    METRIC_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    metric: Global___UsageMetric.ValueType
    value: _builtins.int
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        metric: Global___UsageMetric.ValueType = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["metric", b"metric", "store_id", b"store_id", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReportUsageRequest: _TypeAlias = ReportUsageRequest  # noqa: Y015

@_typing.final
class GetCurrentUsageRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetCurrentUsageRequest: _TypeAlias = GetCurrentUsageRequest  # noqa: Y015

@_typing.final
class GetInvoiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INVOICE_ID_FIELD_NUMBER: _builtins.int
    invoice_id: _builtins.str
    def __init__(
        self,
        *,
        invoice_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["invoice_id", b"invoice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetInvoiceRequest: _TypeAlias = GetInvoiceRequest  # noqa: Y015

@_typing.final
class ListInvoicesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    status: Global___InvoiceStatus.ValueType
    @_builtins.property
    def pagination(self) -> _common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        status: Global___InvoiceStatus.ValueType | None = ...,
        pagination: _common_pb2.Pagination | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_status", b"_status", "pagination", b"pagination", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_status", b"_status", "pagination", b"pagination", "status", b"status", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__status: _TypeAlias = _typing.Literal["status"]  # noqa: Y015
    _WhichOneofArgType__status: _TypeAlias = _typing.Literal["_status", b"_status"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status) -> _WhichOneofReturnType__status | None: ...

Global___ListInvoicesRequest: _TypeAlias = ListInvoicesRequest  # noqa: Y015

@_typing.final
class ListInvoicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INVOICES_FIELD_NUMBER: _builtins.int
    PAGE_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def invoices(self) -> _containers.RepeatedCompositeFieldContainer[Global___Invoice]: ...
    @_builtins.property
    def page_info(self) -> _common_pb2.PageInfo: ...
    def __init__(
        self,
        *,
        invoices: _abc.Iterable[Global___Invoice] | None = ...,
        page_info: _common_pb2.PageInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["invoices", b"invoices", "page_info", b"page_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListInvoicesResponse: _TypeAlias = ListInvoicesResponse  # noqa: Y015

@_typing.final
class CreatePaymentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INVOICE_ID_FIELD_NUMBER: _builtins.int
    METHOD_FIELD_NUMBER: _builtins.int
    invoice_id: _builtins.str
    method: Global___PaymentMethod.ValueType
    def __init__(
        self,
        *,
        invoice_id: _builtins.str = ...,
        method: Global___PaymentMethod.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["invoice_id", b"invoice_id", "method", b"method"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreatePaymentRequest: _TypeAlias = CreatePaymentRequest  # noqa: Y015

@_typing.final
class PaymentCallbackRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PAYMENT_ID_FIELD_NUMBER: _builtins.int
    GATEWAY_RESPONSE_FIELD_NUMBER: _builtins.int
    payment_id: _builtins.str
    gateway_response: _builtins.str
    def __init__(
        self,
        *,
        payment_id: _builtins.str = ...,
        gateway_response: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["gateway_response", b"gateway_response", "payment_id", b"payment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PaymentCallbackRequest: _TypeAlias = PaymentCallbackRequest  # noqa: Y015
