# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from knowledge.v1 import knowledge_pb2 as knowledge_dot_v1_dot_knowledge__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in knowledge/v1/knowledge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateKB = channel.unary_unary(
                '/knowledge.v1.KnowledgeService/CreateKB',
                request_serializer=knowledge_dot_v1_dot_knowledge__pb2.CreateKBRequest.SerializeToString,
                response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.KnowledgeBase.FromString,
                _registered_method=True)
        self.GetKB = channel.unary_unary(
                '/knowledge.v1.KnowledgeService/GetKB',
                request_serializer=knowledge_dot_v1_dot_knowledge__pb2.GetKBRequest.SerializeToString,
                response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.KnowledgeBase.FromString,
                _registered_method=True)
        self.DeleteKB = channel.unary_unary(
                '/knowledge.v1.KnowledgeService/DeleteKB',
                request_serializer=knowledge_dot_v1_dot_knowledge__pb2.DeleteKBRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Error.FromString,
                _registered_method=True)
        self.ListKBs = channel.unary_unary(
                '/knowledge.v1.KnowledgeService/ListKBs',
                request_serializer=knowledge_dot_v1_dot_knowledge__pb2.ListKBsRequest.SerializeToString,
                response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.ListKBsResponse.FromString,
                _registered_method=True)
        self.UploadDocument = channel.unary_unary(
                '/knowledge.v1.KnowledgeService/UploadDocument',
                request_serializer=knowledge_dot_v1_dot_knowledge__pb2.UploadDocumentRequest.SerializeToString,
                response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.Document.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/knowledge.v1.KnowledgeService/DeleteDocument',
                request_serializer=knowledge_dot_v1_dot_knowledge__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Error.FromString,
                _registered_method=True)
        self.CreateFAQ = channel.unary_unary(
                '/knowledge.v1.KnowledgeService/CreateFAQ',
                request_serializer=knowledge_dot_v1_dot_knowledge__pb2.CreateFAQRequest.SerializeToString,
                response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.FAQ.FromString,
                _registered_method=True)
        self.DeleteFAQ = channel.unary_unary(
                '/knowledge.v1.KnowledgeService/DeleteFAQ',
                request_serializer=knowledge_dot_v1_dot_knowledge__pb2.DeleteFAQRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Error.FromString,
                _registered_method=True)
        self.ListFAQs = channel.unary_unary(
                '/knowledge.v1.KnowledgeService/ListFAQs',
                request_serializer=knowledge_dot_v1_dot_knowledge__pb2.ListFAQsRequest.SerializeToString,
                response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.ListFAQsResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/knowledge.v1.KnowledgeService/Search',
                request_serializer=knowledge_dot_v1_dot_knowledge__pb2.SearchRequest.SerializeToString,
                response_deserializer=knowledge_dot_v1_dot_knowledge__pb2.SearchResponse.FromString,
                _registered_method=True)


class KnowledgeServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateKB(self, request, context):
        """── Knowledge Base ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKB(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListKBs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDocument(self, request, context):
        """── Documents ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFAQ(self, request, context):
        """── FAQ ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFAQ(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFAQs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """── Retrieval ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateKB': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateKB,
                    request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.CreateKBRequest.FromString,
                    response_serializer=knowledge_dot_v1_dot_knowledge__pb2.KnowledgeBase.SerializeToString,
            ),
            'GetKB': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKB,
                    request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.GetKBRequest.FromString,
                    response_serializer=knowledge_dot_v1_dot_knowledge__pb2.KnowledgeBase.SerializeToString,
            ),
            'DeleteKB': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKB,
                    request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.DeleteKBRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Error.SerializeToString,
            ),
            'ListKBs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListKBs,
                    request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.ListKBsRequest.FromString,
                    response_serializer=knowledge_dot_v1_dot_knowledge__pb2.ListKBsResponse.SerializeToString,
            ),
            'UploadDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDocument,
                    request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.UploadDocumentRequest.FromString,
                    response_serializer=knowledge_dot_v1_dot_knowledge__pb2.Document.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Error.SerializeToString,
            ),
            'CreateFAQ': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFAQ,
                    request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.CreateFAQRequest.FromString,
                    response_serializer=knowledge_dot_v1_dot_knowledge__pb2.FAQ.SerializeToString,
            ),
            'DeleteFAQ': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFAQ,
                    request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.DeleteFAQRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Error.SerializeToString,
            ),
            'ListFAQs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFAQs,
                    request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.ListFAQsRequest.FromString,
                    response_serializer=knowledge_dot_v1_dot_knowledge__pb2.ListFAQsResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=knowledge_dot_v1_dot_knowledge__pb2.SearchRequest.FromString,
                    response_serializer=knowledge_dot_v1_dot_knowledge__pb2.SearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'knowledge.v1.KnowledgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('knowledge.v1.KnowledgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateKB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge.v1.KnowledgeService/CreateKB',
            knowledge_dot_v1_dot_knowledge__pb2.CreateKBRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.KnowledgeBase.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetKB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge.v1.KnowledgeService/GetKB',
            knowledge_dot_v1_dot_knowledge__pb2.GetKBRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.KnowledgeBase.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKB(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge.v1.KnowledgeService/DeleteKB',
            knowledge_dot_v1_dot_knowledge__pb2.DeleteKBRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListKBs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge.v1.KnowledgeService/ListKBs',
            knowledge_dot_v1_dot_knowledge__pb2.ListKBsRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.ListKBsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge.v1.KnowledgeService/UploadDocument',
            knowledge_dot_v1_dot_knowledge__pb2.UploadDocumentRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.Document.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge.v1.KnowledgeService/DeleteDocument',
            knowledge_dot_v1_dot_knowledge__pb2.DeleteDocumentRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFAQ(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge.v1.KnowledgeService/CreateFAQ',
            knowledge_dot_v1_dot_knowledge__pb2.CreateFAQRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.FAQ.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFAQ(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge.v1.KnowledgeService/DeleteFAQ',
            knowledge_dot_v1_dot_knowledge__pb2.DeleteFAQRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFAQs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge.v1.KnowledgeService/ListFAQs',
            knowledge_dot_v1_dot_knowledge__pb2.ListFAQsRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.ListFAQsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/knowledge.v1.KnowledgeService/Search',
            knowledge_dot_v1_dot_knowledge__pb2.SearchRequest.SerializeToString,
            knowledge_dot_v1_dot_knowledge__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
