apiVersion: v1
kind: Service
metadata:
  name: platform-svc
  labels:
    app.kubernetes.io/name: platform-svc
spec:
  type: ClusterIP
  ports:
    - port: 50050
      targetPort: 50050
      protocol: TCP
      name: grpc
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: platform-svc
