"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Voice Service — Voice/Timbre CRUD, Clone, Speaker Embedding Management

Phase 2: CosyVoice2 Speaker Encoder, 15min → 24h full clone
Phase 3: Few-shot cloning (3-10s audio), GPT-SoVITS / Fish-Speech
"""

from collections import abc as _abc
from common.v1 import common_pb2 as _common_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Gender:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _GenderEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Gender.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    GENDER_UNSPECIFIED: _Gender.ValueType  # 0
    GENDER_MALE: _Gender.ValueType  # 1
    GENDER_FEMALE: _Gender.ValueType  # 2

class Gender(_Gender, metaclass=_GenderEnumTypeWrapper): ...

GENDER_UNSPECIFIED: Gender.ValueType  # 0
GENDER_MALE: Gender.ValueType  # 1
GENDER_FEMALE: Gender.ValueType  # 2
Global___Gender: _TypeAlias = Gender  # noqa: Y015

class _VoiceStyle:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _VoiceStyleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_VoiceStyle.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    VOICE_STYLE_UNSPECIFIED: _VoiceStyle.ValueType  # 0
    VOICE_STYLE_PASSIONATE: _VoiceStyle.ValueType  # 1
    """激情带货"""
    VOICE_STYLE_PROFESSIONAL: _VoiceStyle.ValueType  # 2
    """专业讲解"""
    VOICE_STYLE_GENTLE: _VoiceStyle.ValueType  # 3
    """温柔亲切"""
    VOICE_STYLE_LIVELY: _VoiceStyle.ValueType  # 4
    """活泼活泼"""
    VOICE_STYLE_AUTHORITATIVE: _VoiceStyle.ValueType  # 5
    """权威沉稳 (Phase 2)"""

class VoiceStyle(_VoiceStyle, metaclass=_VoiceStyleEnumTypeWrapper): ...

VOICE_STYLE_UNSPECIFIED: VoiceStyle.ValueType  # 0
VOICE_STYLE_PASSIONATE: VoiceStyle.ValueType  # 1
"""激情带货"""
VOICE_STYLE_PROFESSIONAL: VoiceStyle.ValueType  # 2
"""专业讲解"""
VOICE_STYLE_GENTLE: VoiceStyle.ValueType  # 3
"""温柔亲切"""
VOICE_STYLE_LIVELY: VoiceStyle.ValueType  # 4
"""活泼活泼"""
VOICE_STYLE_AUTHORITATIVE: VoiceStyle.ValueType  # 5
"""权威沉稳 (Phase 2)"""
Global___VoiceStyle: _TypeAlias = VoiceStyle  # noqa: Y015

class _VoiceStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _VoiceStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_VoiceStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    VOICE_STATUS_UNSPECIFIED: _VoiceStatus.ValueType  # 0
    VOICE_STATUS_ACTIVE: _VoiceStatus.ValueType  # 1
    VOICE_STATUS_CLONING: _VoiceStatus.ValueType  # 2
    VOICE_STATUS_FAILED: _VoiceStatus.ValueType  # 3
    VOICE_STATUS_PENDING_AUDIT: _VoiceStatus.ValueType  # 4
    """Awaiting content review"""

class VoiceStatus(_VoiceStatus, metaclass=_VoiceStatusEnumTypeWrapper): ...

VOICE_STATUS_UNSPECIFIED: VoiceStatus.ValueType  # 0
VOICE_STATUS_ACTIVE: VoiceStatus.ValueType  # 1
VOICE_STATUS_CLONING: VoiceStatus.ValueType  # 2
VOICE_STATUS_FAILED: VoiceStatus.ValueType  # 3
VOICE_STATUS_PENDING_AUDIT: VoiceStatus.ValueType  # 4
"""Awaiting content review"""
Global___VoiceStatus: _TypeAlias = VoiceStatus  # noqa: Y015

class _CloneMethod:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CloneMethodEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CloneMethod.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CLONE_METHOD_UNSPECIFIED: _CloneMethod.ValueType  # 0
    CLONE_METHOD_FULL_TRAINING: _CloneMethod.ValueType  # 1
    """15min audio, full CosyVoice2 fine-tune (Phase 2)"""
    CLONE_METHOD_FEW_SHOT: _CloneMethod.ValueType  # 2
    """3-10s audio, GPT-SoVITS / CosyVoice2 zero-shot (Phase 3)"""
    CLONE_METHOD_SPEAKER_ENCODER: _CloneMethod.ValueType  # 3
    """Speaker encoder only, no fine-tuning"""

class CloneMethod(_CloneMethod, metaclass=_CloneMethodEnumTypeWrapper): ...

CLONE_METHOD_UNSPECIFIED: CloneMethod.ValueType  # 0
CLONE_METHOD_FULL_TRAINING: CloneMethod.ValueType  # 1
"""15min audio, full CosyVoice2 fine-tune (Phase 2)"""
CLONE_METHOD_FEW_SHOT: CloneMethod.ValueType  # 2
"""3-10s audio, GPT-SoVITS / CosyVoice2 zero-shot (Phase 3)"""
CLONE_METHOD_SPEAKER_ENCODER: CloneMethod.ValueType  # 3
"""Speaker encoder only, no fine-tuning"""
Global___CloneMethod: _TypeAlias = CloneMethod  # noqa: Y015

class _CloneStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CloneStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CloneStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    CLONE_STATUS_UNSPECIFIED: _CloneStatus.ValueType  # 0
    CLONE_STATUS_UPLOADING: _CloneStatus.ValueType  # 1
    CLONE_STATUS_PREPROCESSING: _CloneStatus.ValueType  # 2
    """Audio denoising, VAD, alignment"""
    CLONE_STATUS_TRAINING: _CloneStatus.ValueType  # 3
    CLONE_STATUS_EVALUATING: _CloneStatus.ValueType  # 4
    """MOS + similarity scoring"""
    CLONE_STATUS_PENDING_AUDIT: _CloneStatus.ValueType  # 5
    CLONE_STATUS_SUCCESS: _CloneStatus.ValueType  # 6
    CLONE_STATUS_FAILED: _CloneStatus.ValueType  # 7
    CLONE_STATUS_CANCELLED: _CloneStatus.ValueType  # 8

class CloneStatus(_CloneStatus, metaclass=_CloneStatusEnumTypeWrapper): ...

CLONE_STATUS_UNSPECIFIED: CloneStatus.ValueType  # 0
CLONE_STATUS_UPLOADING: CloneStatus.ValueType  # 1
CLONE_STATUS_PREPROCESSING: CloneStatus.ValueType  # 2
"""Audio denoising, VAD, alignment"""
CLONE_STATUS_TRAINING: CloneStatus.ValueType  # 3
CLONE_STATUS_EVALUATING: CloneStatus.ValueType  # 4
"""MOS + similarity scoring"""
CLONE_STATUS_PENDING_AUDIT: CloneStatus.ValueType  # 5
CLONE_STATUS_SUCCESS: CloneStatus.ValueType  # 6
CLONE_STATUS_FAILED: CloneStatus.ValueType  # 7
CLONE_STATUS_CANCELLED: CloneStatus.ValueType  # 8
Global___CloneStatus: _TypeAlias = CloneStatus  # noqa: Y015

@_typing.final
class Voice(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_ID_FIELD_NUMBER: _builtins.int
    STORE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    GENDER_FIELD_NUMBER: _builtins.int
    AGE_RANGE_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    IS_PUBLIC_FIELD_NUMBER: _builtins.int
    QUALITY_FIELD_NUMBER: _builtins.int
    AUDIT_INFO_FIELD_NUMBER: _builtins.int
    CLONE_METHOD_FIELD_NUMBER: _builtins.int
    SPEAKER_EMBEDDING_URL_FIELD_NUMBER: _builtins.int
    FEW_SHOT_CONFIG_FIELD_NUMBER: _builtins.int
    voice_id: _builtins.str
    store_id: _builtins.str
    name: _builtins.str
    gender: Global___Gender.ValueType
    age_range: _builtins.str
    language: _builtins.str
    style: Global___VoiceStyle.ValueType
    status: Global___VoiceStatus.ValueType
    is_public: _builtins.bool
    clone_method: Global___CloneMethod.ValueType
    """── Clone-related (Phase 2/3) ──
    Few-shot vs full training
    """
    speaker_embedding_url: _builtins.str
    """MinIO URL of speaker embedding file"""
    @_builtins.property
    def quality(self) -> Global___VoiceQualityMetrics: ...
    @_builtins.property
    def audit_info(self) -> _common_pb2.AuditInfo: ...
    @_builtins.property
    def few_shot_config(self) -> Global___FewShotConfig:
        """Few-shot parameters (Phase 3)"""

    def __init__(
        self,
        *,
        voice_id: _builtins.str = ...,
        store_id: _builtins.str = ...,
        name: _builtins.str = ...,
        gender: Global___Gender.ValueType = ...,
        age_range: _builtins.str = ...,
        language: _builtins.str = ...,
        style: Global___VoiceStyle.ValueType = ...,
        status: Global___VoiceStatus.ValueType = ...,
        is_public: _builtins.bool = ...,
        quality: Global___VoiceQualityMetrics | None = ...,
        audit_info: _common_pb2.AuditInfo | None = ...,
        clone_method: Global___CloneMethod.ValueType = ...,
        speaker_embedding_url: _builtins.str = ...,
        few_shot_config: Global___FewShotConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audit_info", b"audit_info", "few_shot_config", b"few_shot_config", "quality", b"quality"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["age_range", b"age_range", "audit_info", b"audit_info", "clone_method", b"clone_method", "few_shot_config", b"few_shot_config", "gender", b"gender", "is_public", b"is_public", "language", b"language", "name", b"name", "quality", b"quality", "speaker_embedding_url", b"speaker_embedding_url", "status", b"status", "store_id", b"store_id", "style", b"style", "voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Voice: _TypeAlias = Voice  # noqa: Y015

@_typing.final
class VoiceQualityMetrics(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MOS_SCORE_FIELD_NUMBER: _builtins.int
    SIMILARITY_SCORE_FIELD_NUMBER: _builtins.int
    PRONUNCIATION_ACCURACY_FIELD_NUMBER: _builtins.int
    EVALUATED_AT_FIELD_NUMBER: _builtins.int
    mos_score: _builtins.float
    """Mean Opinion Score (1-5)"""
    similarity_score: _builtins.float
    """Speaker similarity (0-1)"""
    pronunciation_accuracy: _builtins.float
    """Phoneme accuracy (0-1)"""
    evaluated_at: _builtins.int
    def __init__(
        self,
        *,
        mos_score: _builtins.float = ...,
        similarity_score: _builtins.float = ...,
        pronunciation_accuracy: _builtins.float = ...,
        evaluated_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["evaluated_at", b"evaluated_at", "mos_score", b"mos_score", "pronunciation_accuracy", b"pronunciation_accuracy", "similarity_score", b"similarity_score"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VoiceQualityMetrics: _TypeAlias = VoiceQualityMetrics  # noqa: Y015

@_typing.final
class FewShotConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REFERENCE_AUDIO_DURATION_SEC_FIELD_NUMBER: _builtins.int
    REFERENCE_AUDIO_URL_FIELD_NUMBER: _builtins.int
    REFERENCE_TRANSCRIPT_FIELD_NUMBER: _builtins.int
    SIMILARITY_THRESHOLD_FIELD_NUMBER: _builtins.int
    reference_audio_duration_sec: _builtins.int
    """Length of reference audio (3-10s)"""
    reference_audio_url: _builtins.str
    """MinIO URL of reference clip"""
    reference_transcript: _builtins.str
    """Transcript of reference audio"""
    similarity_threshold: _builtins.float
    """Minimum acceptable similarity (default 0.85)"""
    def __init__(
        self,
        *,
        reference_audio_duration_sec: _builtins.int = ...,
        reference_audio_url: _builtins.str = ...,
        reference_transcript: _builtins.str = ...,
        similarity_threshold: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reference_audio_duration_sec", b"reference_audio_duration_sec", "reference_audio_url", b"reference_audio_url", "reference_transcript", b"reference_transcript", "similarity_threshold", b"similarity_threshold"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FewShotConfig: _TypeAlias = FewShotConfig  # noqa: Y015

@_typing.final
class SpeakerEmbedding(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_ID_FIELD_NUMBER: _builtins.int
    EMBEDDING_DIM_FIELD_NUMBER: _builtins.int
    EMBEDDING_DATA_FIELD_NUMBER: _builtins.int
    MODEL_VERSION_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    voice_id: _builtins.str
    embedding_dim: _builtins.int
    """e.g. 256 for CosyVoice2"""
    embedding_data: _builtins.bytes
    """Raw float32 embedding bytes"""
    model_version: _builtins.str
    """CosyVoice2 / GPT-SoVITS version"""
    created_at: _builtins.int
    def __init__(
        self,
        *,
        voice_id: _builtins.str = ...,
        embedding_dim: _builtins.int = ...,
        embedding_data: _builtins.bytes = ...,
        model_version: _builtins.str = ...,
        created_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "embedding_data", b"embedding_data", "embedding_dim", b"embedding_dim", "model_version", b"model_version", "voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SpeakerEmbedding: _TypeAlias = SpeakerEmbedding  # noqa: Y015

@_typing.final
class VoiceCloneTask(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    VOICE_ID_FIELD_NUMBER: _builtins.int
    STORE_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    CLONE_METHOD_FIELD_NUMBER: _builtins.int
    PROGRESS_PERCENT_FIELD_NUMBER: _builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: _builtins.int
    SOURCE_AUDIO_URL_FIELD_NUMBER: _builtins.int
    SOURCE_TRANSCRIPT_FIELD_NUMBER: _builtins.int
    CLONE_CONFIG_FIELD_NUMBER: _builtins.int
    QUALITY_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    COMPLETED_AT_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    voice_id: _builtins.str
    store_id: _builtins.str
    """For tenant-scoped queries"""
    status: Global___CloneStatus.ValueType
    clone_method: Global___CloneMethod.ValueType
    """Target clone technique"""
    progress_percent: _builtins.int
    error_message: _builtins.str
    source_audio_url: _builtins.str
    """MinIO URL of uploaded source audio"""
    source_transcript: _builtins.str
    """Optional: transcript for alignment"""
    created_at: _builtins.int
    completed_at: _builtins.int
    @_builtins.property
    def clone_config(self) -> Global___CloneConfig:
        """Clone-specific parameters"""

    @_builtins.property
    def quality(self) -> Global___VoiceQualityMetrics:
        """Post-clone evaluation (on success)"""

    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        voice_id: _builtins.str = ...,
        store_id: _builtins.str = ...,
        status: Global___CloneStatus.ValueType = ...,
        clone_method: Global___CloneMethod.ValueType = ...,
        progress_percent: _builtins.int = ...,
        error_message: _builtins.str = ...,
        source_audio_url: _builtins.str = ...,
        source_transcript: _builtins.str = ...,
        clone_config: Global___CloneConfig | None = ...,
        quality: Global___VoiceQualityMetrics | None = ...,
        created_at: _builtins.int = ...,
        completed_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["clone_config", b"clone_config", "quality", b"quality"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clone_config", b"clone_config", "clone_method", b"clone_method", "completed_at", b"completed_at", "created_at", b"created_at", "error_message", b"error_message", "progress_percent", b"progress_percent", "quality", b"quality", "source_audio_url", b"source_audio_url", "source_transcript", b"source_transcript", "status", b"status", "store_id", b"store_id", "task_id", b"task_id", "voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VoiceCloneTask: _TypeAlias = VoiceCloneTask  # noqa: Y015

@_typing.final
class CloneConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ENABLE_EMOTION_CLONING_FIELD_NUMBER: _builtins.int
    ENABLE_STYLE_TRANSFER_FIELD_NUMBER: _builtins.int
    TARGET_SAMPLE_RATE_FIELD_NUMBER: _builtins.int
    EMOTION_PRESETS_FIELD_NUMBER: _builtins.int
    enable_emotion_cloning: _builtins.bool
    """Clone emotional expressiveness"""
    enable_style_transfer: _builtins.bool
    """Transfer speaking style"""
    target_sample_rate: _builtins.int
    """Default 24000"""
    emotion_presets: _builtins.str
    """Comma-separated: "happy,sad,angry,neutral" """
    def __init__(
        self,
        *,
        enable_emotion_cloning: _builtins.bool = ...,
        enable_style_transfer: _builtins.bool = ...,
        target_sample_rate: _builtins.int = ...,
        emotion_presets: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["emotion_presets", b"emotion_presets", "enable_emotion_cloning", b"enable_emotion_cloning", "enable_style_transfer", b"enable_style_transfer", "target_sample_rate", b"target_sample_rate"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CloneConfig: _TypeAlias = CloneConfig  # noqa: Y015

@_typing.final
class CreateVoiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    GENDER_FIELD_NUMBER: _builtins.int
    AGE_RANGE_FIELD_NUMBER: _builtins.int
    LANGUAGE_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    PROMPT_AUDIO_URL_FIELD_NUMBER: _builtins.int
    PROMPT_TRANSCRIPT_FIELD_NUMBER: _builtins.int
    CLONE_METHOD_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    name: _builtins.str
    gender: Global___Gender.ValueType
    age_range: _builtins.str
    language: _builtins.str
    style: Global___VoiceStyle.ValueType
    prompt_audio_url: _builtins.str
    """MinIO URL (not raw bytes)"""
    prompt_transcript: _builtins.str
    clone_method: Global___CloneMethod.ValueType
    """Required if cloning"""
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        name: _builtins.str = ...,
        gender: Global___Gender.ValueType = ...,
        age_range: _builtins.str = ...,
        language: _builtins.str = ...,
        style: Global___VoiceStyle.ValueType = ...,
        prompt_audio_url: _builtins.str = ...,
        prompt_transcript: _builtins.str = ...,
        clone_method: Global___CloneMethod.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["age_range", b"age_range", "clone_method", b"clone_method", "gender", b"gender", "language", b"language", "name", b"name", "prompt_audio_url", b"prompt_audio_url", "prompt_transcript", b"prompt_transcript", "store_id", b"store_id", "style", b"style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateVoiceRequest: _TypeAlias = CreateVoiceRequest  # noqa: Y015

@_typing.final
class GetVoiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_ID_FIELD_NUMBER: _builtins.int
    voice_id: _builtins.str
    def __init__(
        self,
        *,
        voice_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetVoiceRequest: _TypeAlias = GetVoiceRequest  # noqa: Y015

@_typing.final
class UpdateVoiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    voice_id: _builtins.str
    name: _builtins.str
    style: Global___VoiceStyle.ValueType
    def __init__(
        self,
        *,
        voice_id: _builtins.str = ...,
        name: _builtins.str | None = ...,
        style: Global___VoiceStyle.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "_style", b"_style", "name", b"name", "style", b"style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_name", b"_name", "_style", b"_style", "name", b"name", "style", b"style", "voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__name: _TypeAlias = _typing.Literal["name"]  # noqa: Y015
    _WhichOneofArgType__name: _TypeAlias = _typing.Literal["_name", b"_name"]  # noqa: Y015
    _WhichOneofReturnType__style: _TypeAlias = _typing.Literal["style"]  # noqa: Y015
    _WhichOneofArgType__style: _TypeAlias = _typing.Literal["_style", b"_style"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__name) -> _WhichOneofReturnType__name | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__style) -> _WhichOneofReturnType__style | None: ...

Global___UpdateVoiceRequest: _TypeAlias = UpdateVoiceRequest  # noqa: Y015

@_typing.final
class DeleteVoiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_ID_FIELD_NUMBER: _builtins.int
    voice_id: _builtins.str
    def __init__(
        self,
        *,
        voice_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteVoiceRequest: _TypeAlias = DeleteVoiceRequest  # noqa: Y015

@_typing.final
class ListVoicesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    GENDER_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    CLONE_METHOD_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    gender: Global___Gender.ValueType
    style: Global___VoiceStyle.ValueType
    clone_method: Global___CloneMethod.ValueType
    """Filter cloned voices by method"""
    @_builtins.property
    def pagination(self) -> _common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        gender: Global___Gender.ValueType | None = ...,
        style: Global___VoiceStyle.ValueType | None = ...,
        clone_method: Global___CloneMethod.ValueType | None = ...,
        pagination: _common_pb2.Pagination | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_clone_method", b"_clone_method", "_gender", b"_gender", "_style", b"_style", "clone_method", b"clone_method", "gender", b"gender", "pagination", b"pagination", "style", b"style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_clone_method", b"_clone_method", "_gender", b"_gender", "_style", b"_style", "clone_method", b"clone_method", "gender", b"gender", "pagination", b"pagination", "store_id", b"store_id", "style", b"style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__clone_method: _TypeAlias = _typing.Literal["clone_method"]  # noqa: Y015
    _WhichOneofArgType__clone_method: _TypeAlias = _typing.Literal["_clone_method", b"_clone_method"]  # noqa: Y015
    _WhichOneofReturnType__gender: _TypeAlias = _typing.Literal["gender"]  # noqa: Y015
    _WhichOneofArgType__gender: _TypeAlias = _typing.Literal["_gender", b"_gender"]  # noqa: Y015
    _WhichOneofReturnType__style: _TypeAlias = _typing.Literal["style"]  # noqa: Y015
    _WhichOneofArgType__style: _TypeAlias = _typing.Literal["_style", b"_style"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__clone_method) -> _WhichOneofReturnType__clone_method | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__gender) -> _WhichOneofReturnType__gender | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__style) -> _WhichOneofReturnType__style | None: ...

Global___ListVoicesRequest: _TypeAlias = ListVoicesRequest  # noqa: Y015

@_typing.final
class ListVoicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICES_FIELD_NUMBER: _builtins.int
    PAGE_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def voices(self) -> _containers.RepeatedCompositeFieldContainer[Global___Voice]: ...
    @_builtins.property
    def page_info(self) -> _common_pb2.PageInfo: ...
    def __init__(
        self,
        *,
        voices: _abc.Iterable[Global___Voice] | None = ...,
        page_info: _common_pb2.PageInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info", "voices", b"voices"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListVoicesResponse: _TypeAlias = ListVoicesResponse  # noqa: Y015

@_typing.final
class StartVoiceCloneRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_ID_FIELD_NUMBER: _builtins.int
    SOURCE_AUDIO_URL_FIELD_NUMBER: _builtins.int
    SOURCE_TRANSCRIPT_FIELD_NUMBER: _builtins.int
    CLONE_METHOD_FIELD_NUMBER: _builtins.int
    CLONE_CONFIG_FIELD_NUMBER: _builtins.int
    voice_id: _builtins.str
    source_audio_url: _builtins.str
    """MinIO URL (not raw bytes)"""
    source_transcript: _builtins.str
    """Optional transcript for alignment"""
    clone_method: Global___CloneMethod.ValueType
    @_builtins.property
    def clone_config(self) -> Global___CloneConfig: ...
    def __init__(
        self,
        *,
        voice_id: _builtins.str = ...,
        source_audio_url: _builtins.str = ...,
        source_transcript: _builtins.str = ...,
        clone_method: Global___CloneMethod.ValueType = ...,
        clone_config: Global___CloneConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["clone_config", b"clone_config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["clone_config", b"clone_config", "clone_method", b"clone_method", "source_audio_url", b"source_audio_url", "source_transcript", b"source_transcript", "voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartVoiceCloneRequest: _TypeAlias = StartVoiceCloneRequest  # noqa: Y015

@_typing.final
class GetVoiceCloneTaskRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetVoiceCloneTaskRequest: _TypeAlias = GetVoiceCloneTaskRequest  # noqa: Y015

@_typing.final
class ListVoiceCloneTasksRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    status: Global___CloneStatus.ValueType
    @_builtins.property
    def pagination(self) -> _common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        status: Global___CloneStatus.ValueType | None = ...,
        pagination: _common_pb2.Pagination | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_status", b"_status", "pagination", b"pagination", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_status", b"_status", "pagination", b"pagination", "status", b"status", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__status: _TypeAlias = _typing.Literal["status"]  # noqa: Y015
    _WhichOneofArgType__status: _TypeAlias = _typing.Literal["_status", b"_status"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status) -> _WhichOneofReturnType__status | None: ...

Global___ListVoiceCloneTasksRequest: _TypeAlias = ListVoiceCloneTasksRequest  # noqa: Y015

@_typing.final
class ListVoiceCloneTasksResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASKS_FIELD_NUMBER: _builtins.int
    PAGE_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tasks(self) -> _containers.RepeatedCompositeFieldContainer[Global___VoiceCloneTask]: ...
    @_builtins.property
    def page_info(self) -> _common_pb2.PageInfo: ...
    def __init__(
        self,
        *,
        tasks: _abc.Iterable[Global___VoiceCloneTask] | None = ...,
        page_info: _common_pb2.PageInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info", "tasks", b"tasks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListVoiceCloneTasksResponse: _TypeAlias = ListVoiceCloneTasksResponse  # noqa: Y015

@_typing.final
class CancelVoiceCloneRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CancelVoiceCloneRequest: _TypeAlias = CancelVoiceCloneRequest  # noqa: Y015

@_typing.final
class GetSpeakerEmbeddingRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_ID_FIELD_NUMBER: _builtins.int
    voice_id: _builtins.str
    def __init__(
        self,
        *,
        voice_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSpeakerEmbeddingRequest: _TypeAlias = GetSpeakerEmbeddingRequest  # noqa: Y015

@_typing.final
class CompareVoicesRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_ID_1_FIELD_NUMBER: _builtins.int
    VOICE_ID_2_FIELD_NUMBER: _builtins.int
    voice_id_1: _builtins.str
    voice_id_2: _builtins.str
    def __init__(
        self,
        *,
        voice_id_1: _builtins.str = ...,
        voice_id_2: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["voice_id_1", b"voice_id_1", "voice_id_2", b"voice_id_2"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CompareVoicesRequest: _TypeAlias = CompareVoicesRequest  # noqa: Y015

@_typing.final
class CompareVoicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SIMILARITY_SCORE_FIELD_NUMBER: _builtins.int
    similarity_score: _builtins.float
    """Cosine similarity of embeddings"""
    def __init__(
        self,
        *,
        similarity_score: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["similarity_score", b"similarity_score"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CompareVoicesResponse: _TypeAlias = CompareVoicesResponse  # noqa: Y015

@_typing.final
class PreviewVoiceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOICE_ID_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    EMOTION_FIELD_NUMBER: _builtins.int
    voice_id: _builtins.str
    text: _builtins.str
    emotion: _builtins.str
    """Override emotion for preview"""
    def __init__(
        self,
        *,
        voice_id: _builtins.str = ...,
        text: _builtins.str = ...,
        emotion: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_emotion", b"_emotion", "emotion", b"emotion"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_emotion", b"_emotion", "emotion", b"emotion", "text", b"text", "voice_id", b"voice_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__emotion: _TypeAlias = _typing.Literal["emotion"]  # noqa: Y015
    _WhichOneofArgType__emotion: _TypeAlias = _typing.Literal["_emotion", b"_emotion"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__emotion) -> _WhichOneofReturnType__emotion | None: ...

Global___PreviewVoiceRequest: _TypeAlias = PreviewVoiceRequest  # noqa: Y015

@_typing.final
class PreviewVoiceResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PREVIEW_URL_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    preview_url: _builtins.str
    duration_ms: _builtins.int
    def __init__(
        self,
        *,
        preview_url: _builtins.str = ...,
        duration_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_ms", b"duration_ms", "preview_url", b"preview_url"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PreviewVoiceResponse: _TypeAlias = PreviewVoiceResponse  # noqa: Y015
