# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from audit.v1 import audit_pb2 as audit_dot_v1_dot_audit__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audit/v1/audit_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuditServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AuditAvatar = channel.unary_unary(
                '/audit.v1.AuditService/AuditAvatar',
                request_serializer=audit_dot_v1_dot_audit__pb2.AuditAvatarRequest.SerializeToString,
                response_deserializer=audit_dot_v1_dot_audit__pb2.AuditResult.FromString,
                _registered_method=True)
        self.AuditScript = channel.unary_unary(
                '/audit.v1.AuditService/AuditScript',
                request_serializer=audit_dot_v1_dot_audit__pb2.AuditScriptRequest.SerializeToString,
                response_deserializer=audit_dot_v1_dot_audit__pb2.AuditResult.FromString,
                _registered_method=True)
        self.SubmitScreenshot = channel.unary_unary(
                '/audit.v1.AuditService/SubmitScreenshot',
                request_serializer=audit_dot_v1_dot_audit__pb2.SubmitScreenshotRequest.SerializeToString,
                response_deserializer=audit_dot_v1_dot_audit__pb2.AuditResult.FromString,
                _registered_method=True)
        self.ReportViolation = channel.unary_unary(
                '/audit.v1.AuditService/ReportViolation',
                request_serializer=audit_dot_v1_dot_audit__pb2.ReportViolationRequest.SerializeToString,
                response_deserializer=audit_dot_v1_dot_audit__pb2.AuditResult.FromString,
                _registered_method=True)
        self.GetAuditLog = channel.unary_unary(
                '/audit.v1.AuditService/GetAuditLog',
                request_serializer=audit_dot_v1_dot_audit__pb2.GetAuditLogRequest.SerializeToString,
                response_deserializer=audit_dot_v1_dot_audit__pb2.AuditLog.FromString,
                _registered_method=True)
        self.ListAuditLogs = channel.unary_unary(
                '/audit.v1.AuditService/ListAuditLogs',
                request_serializer=audit_dot_v1_dot_audit__pb2.ListAuditLogsRequest.SerializeToString,
                response_deserializer=audit_dot_v1_dot_audit__pb2.ListAuditLogsResponse.FromString,
                _registered_method=True)


class AuditServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def AuditAvatar(self, request, context):
        """── Pre-flight Checks ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuditScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitScreenshot(self, request, context):
        """── Live Monitoring ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportViolation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuditLog(self, request, context):
        """── Post-session Archive ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAuditLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuditServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AuditAvatar': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditAvatar,
                    request_deserializer=audit_dot_v1_dot_audit__pb2.AuditAvatarRequest.FromString,
                    response_serializer=audit_dot_v1_dot_audit__pb2.AuditResult.SerializeToString,
            ),
            'AuditScript': grpc.unary_unary_rpc_method_handler(
                    servicer.AuditScript,
                    request_deserializer=audit_dot_v1_dot_audit__pb2.AuditScriptRequest.FromString,
                    response_serializer=audit_dot_v1_dot_audit__pb2.AuditResult.SerializeToString,
            ),
            'SubmitScreenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitScreenshot,
                    request_deserializer=audit_dot_v1_dot_audit__pb2.SubmitScreenshotRequest.FromString,
                    response_serializer=audit_dot_v1_dot_audit__pb2.AuditResult.SerializeToString,
            ),
            'ReportViolation': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportViolation,
                    request_deserializer=audit_dot_v1_dot_audit__pb2.ReportViolationRequest.FromString,
                    response_serializer=audit_dot_v1_dot_audit__pb2.AuditResult.SerializeToString,
            ),
            'GetAuditLog': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuditLog,
                    request_deserializer=audit_dot_v1_dot_audit__pb2.GetAuditLogRequest.FromString,
                    response_serializer=audit_dot_v1_dot_audit__pb2.AuditLog.SerializeToString,
            ),
            'ListAuditLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAuditLogs,
                    request_deserializer=audit_dot_v1_dot_audit__pb2.ListAuditLogsRequest.FromString,
                    response_serializer=audit_dot_v1_dot_audit__pb2.ListAuditLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audit.v1.AuditService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audit.v1.AuditService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuditService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AuditAvatar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audit.v1.AuditService/AuditAvatar',
            audit_dot_v1_dot_audit__pb2.AuditAvatarRequest.SerializeToString,
            audit_dot_v1_dot_audit__pb2.AuditResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuditScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audit.v1.AuditService/AuditScript',
            audit_dot_v1_dot_audit__pb2.AuditScriptRequest.SerializeToString,
            audit_dot_v1_dot_audit__pb2.AuditResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitScreenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audit.v1.AuditService/SubmitScreenshot',
            audit_dot_v1_dot_audit__pb2.SubmitScreenshotRequest.SerializeToString,
            audit_dot_v1_dot_audit__pb2.AuditResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportViolation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audit.v1.AuditService/ReportViolation',
            audit_dot_v1_dot_audit__pb2.ReportViolationRequest.SerializeToString,
            audit_dot_v1_dot_audit__pb2.AuditResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuditLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audit.v1.AuditService/GetAuditLog',
            audit_dot_v1_dot_audit__pb2.GetAuditLogRequest.SerializeToString,
            audit_dot_v1_dot_audit__pb2.AuditLog.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAuditLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audit.v1.AuditService/ListAuditLogs',
            audit_dot_v1_dot_audit__pb2.ListAuditLogsRequest.SerializeToString,
            audit_dot_v1_dot_audit__pb2.ListAuditLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
