"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Audit Service — Compliance Review, Content Moderation, 3-Tier Risk Control"""

from collections import abc as _abc
from common.v1 import common_pb2 as _common_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _AuditVerdict:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AuditVerdictEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AuditVerdict.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    AUDIT_VERDICT_UNSPECIFIED: _AuditVerdict.ValueType  # 0
    AUDIT_VERDICT_APPROVED: _AuditVerdict.ValueType  # 1
    AUDIT_VERDICT_REJECTED: _AuditVerdict.ValueType  # 2
    AUDIT_VERDICT_MANUAL_REVIEW: _AuditVerdict.ValueType  # 3

class AuditVerdict(_AuditVerdict, metaclass=_AuditVerdictEnumTypeWrapper): ...

AUDIT_VERDICT_UNSPECIFIED: AuditVerdict.ValueType  # 0
AUDIT_VERDICT_APPROVED: AuditVerdict.ValueType  # 1
AUDIT_VERDICT_REJECTED: AuditVerdict.ValueType  # 2
AUDIT_VERDICT_MANUAL_REVIEW: AuditVerdict.ValueType  # 3
Global___AuditVerdict: _TypeAlias = AuditVerdict  # noqa: Y015

class _Severity:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SeverityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Severity.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SEVERITY_UNSPECIFIED: _Severity.ValueType  # 0
    SEVERITY_LOW: _Severity.ValueType  # 1
    SEVERITY_MEDIUM: _Severity.ValueType  # 2
    SEVERITY_HIGH: _Severity.ValueType  # 3
    SEVERITY_CRITICAL: _Severity.ValueType  # 4

class Severity(_Severity, metaclass=_SeverityEnumTypeWrapper): ...

SEVERITY_UNSPECIFIED: Severity.ValueType  # 0
SEVERITY_LOW: Severity.ValueType  # 1
SEVERITY_MEDIUM: Severity.ValueType  # 2
SEVERITY_HIGH: Severity.ValueType  # 3
SEVERITY_CRITICAL: Severity.ValueType  # 4
Global___Severity: _TypeAlias = Severity  # noqa: Y015

class _RiskLevel:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RiskLevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RiskLevel.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RISK_LEVEL_UNSPECIFIED: _RiskLevel.ValueType  # 0
    RISK_LEVEL_SAFE: _RiskLevel.ValueType  # 1
    RISK_LEVEL_LOW: _RiskLevel.ValueType  # 2
    RISK_LEVEL_MEDIUM: _RiskLevel.ValueType  # 3
    RISK_LEVEL_HIGH: _RiskLevel.ValueType  # 4

class RiskLevel(_RiskLevel, metaclass=_RiskLevelEnumTypeWrapper): ...

RISK_LEVEL_UNSPECIFIED: RiskLevel.ValueType  # 0
RISK_LEVEL_SAFE: RiskLevel.ValueType  # 1
RISK_LEVEL_LOW: RiskLevel.ValueType  # 2
RISK_LEVEL_MEDIUM: RiskLevel.ValueType  # 3
RISK_LEVEL_HIGH: RiskLevel.ValueType  # 4
Global___RiskLevel: _TypeAlias = RiskLevel  # noqa: Y015

@_typing.final
class AuditResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUDIT_ID_FIELD_NUMBER: _builtins.int
    TARGET_TYPE_FIELD_NUMBER: _builtins.int
    TARGET_ID_FIELD_NUMBER: _builtins.int
    VERDICT_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    VIOLATIONS_FIELD_NUMBER: _builtins.int
    AUDITED_AT_FIELD_NUMBER: _builtins.int
    AUDITOR_FIELD_NUMBER: _builtins.int
    audit_id: _builtins.str
    target_type: _builtins.str
    target_id: _builtins.str
    verdict: Global___AuditVerdict.ValueType
    reason: _builtins.str
    audited_at: _builtins.int
    auditor: _builtins.str
    """"system" or human reviewer ID"""
    @_builtins.property
    def violations(self) -> _containers.RepeatedCompositeFieldContainer[Global___Violation]: ...
    def __init__(
        self,
        *,
        audit_id: _builtins.str = ...,
        target_type: _builtins.str = ...,
        target_id: _builtins.str = ...,
        verdict: Global___AuditVerdict.ValueType = ...,
        reason: _builtins.str = ...,
        violations: _abc.Iterable[Global___Violation] | None = ...,
        audited_at: _builtins.int = ...,
        auditor: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audit_id", b"audit_id", "audited_at", b"audited_at", "auditor", b"auditor", "reason", b"reason", "target_id", b"target_id", "target_type", b"target_type", "verdict", b"verdict", "violations", b"violations"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuditResult: _TypeAlias = AuditResult  # noqa: Y015

@_typing.final
class Violation(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CATEGORY_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    category: _builtins.str
    description: _builtins.str
    severity: Global___Severity.ValueType
    def __init__(
        self,
        *,
        category: _builtins.str = ...,
        description: _builtins.str = ...,
        severity: Global___Severity.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["category", b"category", "description", b"description", "severity", b"severity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Violation: _TypeAlias = Violation  # noqa: Y015

@_typing.final
class AuditLog(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUDIT_LOG_ID_FIELD_NUMBER: _builtins.int
    SESSION_ID_FIELD_NUMBER: _builtins.int
    LIVE_ROOM_ID_FIELD_NUMBER: _builtins.int
    RESULTS_FIELD_NUMBER: _builtins.int
    VIOLATION_COUNT_FIELD_NUMBER: _builtins.int
    RISK_LEVEL_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    audit_log_id: _builtins.str
    session_id: _builtins.str
    live_room_id: _builtins.str
    violation_count: _builtins.int
    risk_level: Global___RiskLevel.ValueType
    created_at: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___AuditResult]: ...
    def __init__(
        self,
        *,
        audit_log_id: _builtins.str = ...,
        session_id: _builtins.str = ...,
        live_room_id: _builtins.str = ...,
        results: _abc.Iterable[Global___AuditResult] | None = ...,
        violation_count: _builtins.int = ...,
        risk_level: Global___RiskLevel.ValueType = ...,
        created_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audit_log_id", b"audit_log_id", "created_at", b"created_at", "live_room_id", b"live_room_id", "results", b"results", "risk_level", b"risk_level", "session_id", b"session_id", "violation_count", b"violation_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuditLog: _TypeAlias = AuditLog  # noqa: Y015

@_typing.final
class AuditAvatarRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AVATAR_ID_FIELD_NUMBER: _builtins.int
    THUMBNAIL_FIELD_NUMBER: _builtins.int
    CELEBRITY_CHECK_FIELD_NUMBER: _builtins.int
    avatar_id: _builtins.str
    thumbnail: _builtins.bytes
    celebrity_check: _builtins.str
    def __init__(
        self,
        *,
        avatar_id: _builtins.str = ...,
        thumbnail: _builtins.bytes = ...,
        celebrity_check: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["avatar_id", b"avatar_id", "celebrity_check", b"celebrity_check", "thumbnail", b"thumbnail"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuditAvatarRequest: _TypeAlias = AuditAvatarRequest  # noqa: Y015

@_typing.final
class AuditScriptRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCRIPT_ID_FIELD_NUMBER: _builtins.int
    FULL_TEXT_FIELD_NUMBER: _builtins.int
    script_id: _builtins.str
    full_text: _builtins.str
    def __init__(
        self,
        *,
        script_id: _builtins.str = ...,
        full_text: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["full_text", b"full_text", "script_id", b"script_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuditScriptRequest: _TypeAlias = AuditScriptRequest  # noqa: Y015

@_typing.final
class SubmitScreenshotRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIVE_ROOM_ID_FIELD_NUMBER: _builtins.int
    IMAGE_DATA_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    live_room_id: _builtins.str
    image_data: _builtins.bytes
    timestamp: _builtins.int
    def __init__(
        self,
        *,
        live_room_id: _builtins.str = ...,
        image_data: _builtins.bytes = ...,
        timestamp: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["image_data", b"image_data", "live_room_id", b"live_room_id", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SubmitScreenshotRequest: _TypeAlias = SubmitScreenshotRequest  # noqa: Y015

@_typing.final
class ReportViolationRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIVE_ROOM_ID_FIELD_NUMBER: _builtins.int
    VIOLATION_TYPE_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    EVIDENCE_URL_FIELD_NUMBER: _builtins.int
    live_room_id: _builtins.str
    violation_type: _builtins.str
    description: _builtins.str
    evidence_url: _builtins.str
    def __init__(
        self,
        *,
        live_room_id: _builtins.str = ...,
        violation_type: _builtins.str = ...,
        description: _builtins.str = ...,
        evidence_url: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "evidence_url", b"evidence_url", "live_room_id", b"live_room_id", "violation_type", b"violation_type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReportViolationRequest: _TypeAlias = ReportViolationRequest  # noqa: Y015

@_typing.final
class GetAuditLogRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    AUDIT_LOG_ID_FIELD_NUMBER: _builtins.int
    audit_log_id: _builtins.str
    def __init__(
        self,
        *,
        audit_log_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audit_log_id", b"audit_log_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetAuditLogRequest: _TypeAlias = GetAuditLogRequest  # noqa: Y015

@_typing.final
class ListAuditLogsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    RISK_LEVEL_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    risk_level: Global___RiskLevel.ValueType
    @_builtins.property
    def pagination(self) -> _common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        risk_level: Global___RiskLevel.ValueType | None = ...,
        pagination: _common_pb2.Pagination | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_risk_level", b"_risk_level", "pagination", b"pagination", "risk_level", b"risk_level"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_risk_level", b"_risk_level", "pagination", b"pagination", "risk_level", b"risk_level", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__risk_level: _TypeAlias = _typing.Literal["risk_level"]  # noqa: Y015
    _WhichOneofArgType__risk_level: _TypeAlias = _typing.Literal["_risk_level", b"_risk_level"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__risk_level) -> _WhichOneofReturnType__risk_level | None: ...

Global___ListAuditLogsRequest: _TypeAlias = ListAuditLogsRequest  # noqa: Y015

@_typing.final
class ListAuditLogsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LOGS_FIELD_NUMBER: _builtins.int
    PAGE_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def logs(self) -> _containers.RepeatedCompositeFieldContainer[Global___AuditLog]: ...
    @_builtins.property
    def page_info(self) -> _common_pb2.PageInfo: ...
    def __init__(
        self,
        *,
        logs: _abc.Iterable[Global___AuditLog] | None = ...,
        page_info: _common_pb2.PageInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["logs", b"logs", "page_info", b"page_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListAuditLogsResponse: _TypeAlias = ListAuditLogsResponse  # noqa: Y015
