apiVersion: v1
kind: Service
metadata:
  name: voice-svc
  namespace: livestream-tts
  labels:
    app: voice-svc
    service: voice
spec:
  type: ClusterIP
  selector:
    app: voice-svc
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8007
      targetPort: http
      protocol: TCP
