"""
Core domain models for the interaction service.

Mirrors interact.v1 proto definitions in Python-native dataclasses.
Used throughout the pipeline for type-safe internal communication.
"""

from __future__ import annotations

import time
import uuid
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Any


# ── Enums (mirroring proto) ──


class SessionStatus(IntEnum):
    UNSPECIFIED = 0
    RUNNING = 1
    PAUSED = 2
    STOPPED = 3


class Channel(IntEnum):
    UNSPECIFIED = 0
    VOICE = 1
    TEXT = 2
    BOTH = 3
    IGNORE = 4


class ModeratorActionType(IntEnum):
    UNSPECIFIED = 0
    SEND_COMMENT = 1
    POP_COUPON = 2
    POP_PRODUCT_CARD = 3
    HIDE_COMMENT = 4
    PIN_COMMENT = 5
    NO_ACTION = 6


# ── Data classes ──


@dataclass
class ModeratorConfig:
    """Configuration for the AI text moderator (field control)."""

    moderator_account_id: str = "mod_official"
    auto_send_comments: bool = True
    auto_send_coupons: bool = True
    auto_send_product_card: bool = True
    auto_hide_negative: bool = True
    comment_interval_seconds: float = 30.0


@dataclass
class SessionConfig:
    """Configuration for a live interaction session."""

    voice_id: str = "default"
    avatar_id: str = "default"
    system_prompt: str = ""
    banned_words: list[str] = field(default_factory=list)
    enable_moderator: bool = True
    enable_product_card: bool = True
    reply_threshold: float = 0.3
    moderator_config: ModeratorConfig = field(default_factory=ModeratorConfig)


@dataclass
class SessionStats:
    """Runtime statistics for a session."""

    total_danmaku: int = 0
    voice_replies: int = 0
    text_replies: int = 0
    moderator_actions: int = 0
    ignored_messages: int = 0
    avg_latency_ms: float = 0.0


@dataclass
class Session:
    """A live interaction session."""

    session_id: str = ""
    live_room_id: str = ""
    store_id: str = ""
    config: SessionConfig = field(default_factory=SessionConfig)
    status: SessionStatus = SessionStatus.UNSPECIFIED
    stats: SessionStats = field(default_factory=SessionStats)
    started_at: int = 0
    ended_at: int = 0

    @classmethod
    def create(cls, live_room_id: str, config: SessionConfig, store_id: str = "") -> Session:
        now_ms = int(time.time() * 1000)
        return cls(
            session_id=f"ses_{uuid.uuid4().hex[:16]}",
            live_room_id=live_room_id,
            store_id=store_id,
            config=config,
            status=SessionStatus.RUNNING,
            started_at=now_ms,
        )


@dataclass
class ModeratorAction:
    """Action produced by the AI text moderator."""

    action_type: ModeratorActionType = ModeratorActionType.NO_ACTION
    comment_text: str = ""
    coupon_id: str = ""
    product_id: str = ""
    hide_comment_id: str = ""


@dataclass
class DanmakuEvent:
    """A parsed danmaku message flowing through the pipeline."""

    danmaku_id: str = ""
    session_id: str = ""
    text: str = ""
    platform_user_id: str = ""
    platform: str = ""  # taobao, douyin, jd, kuaishou
    timestamp: int = 0

    # Enriched by pipeline stages
    intent: int = 0  # nlp.v1.IntentCategory value
    intent_confidence: float = 0.0
    sentiment: int = 0  # nlp.v1.Sentiment value
    sentiment_intensity: float = 0.0
    needs_reply: bool = False

    user_profile: dict[str, Any] = field(default_factory=dict)
    channel: Channel = Channel.UNSPECIFIED
    route_reason: str = ""


@dataclass
class RouteResult:
    """Result of the channel router decision."""

    channel: Channel = Channel.UNSPECIFIED
    reason: str = ""


@dataclass
class ReplyRecord:
    """Record of a reply generated by the pipeline."""

    reply_id: str = ""
    session_id: str = ""
    danmaku_id: str = ""
    channel: Channel = Channel.UNSPECIFIED
    reply_text: str = ""
    emotion: int = 0  # tts.v1.Emotion value
    action: str = ""  # wave_hand, point_product, show_detail, show_product_card
    coupon_ids: list[str] = field(default_factory=list)
    pipeline_latency_ms: float = 0.0
    created_at: int = 0

    @classmethod
    def create(
        cls,
        session_id: str,
        danmaku_id: str,
        channel: Channel,
        reply_text: str = "",
        emotion: int = 0,
        action: str = "",
        coupon_ids: list[str] | None = None,
        latency_ms: float = 0.0,
    ) -> ReplyRecord:
        return cls(
            reply_id=f"rep_{uuid.uuid4().hex[:16]}",
            session_id=session_id,
            danmaku_id=danmaku_id,
            channel=channel,
            reply_text=reply_text,
            emotion=emotion,
            action=action,
            coupon_ids=coupon_ids or [],
            pipeline_latency_ms=latency_ms,
            created_at=int(time.time() * 1000),
        )
