apiVersion: v1
kind: Service
metadata:
  name: script-svc
  labels:
    app: script-svc
spec:
  type: ClusterIP
  selector:
    app: script-svc
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
