apiVersion: v1
kind: ConfigMap
metadata:
  name: product-svc-config
  namespace: livestream-tts
  labels:
    app: product-svc
data:
  DB_HOST: "postgresql.livestream-tts.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "livestream_tts"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.livestream-tts.svc.cluster.local:9093"
  GRPC_PORT: "50051"
  HTTP_PORT: "8003"
