apiVersion: v1
kind: Service
metadata:
  name: product-svc
  namespace: livestream-tts
  labels:
    app: product-svc
    service: product
spec:
  type: ClusterIP
  selector:
    app: product-svc
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc
      protocol: TCP
    - name: http
      port: 8003
      targetPort: http
      protocol: TCP
