apiVersion: v1
kind: Service
metadata:
  name: audit-svc
  namespace: livestream-tts
  labels:
    app: audit-svc
spec:
  selector:
    app: audit-svc
  ports:
    - name: http
      port: 8016
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc
  type: ClusterIP
