# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from script.v1 import script_pb2 as script_dot_v1_dot_script__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in script/v1/script_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScriptServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateScript = channel.unary_unary(
                '/script.v1.ScriptService/CreateScript',
                request_serializer=script_dot_v1_dot_script__pb2.CreateScriptRequest.SerializeToString,
                response_deserializer=script_dot_v1_dot_script__pb2.Script.FromString,
                _registered_method=True)
        self.GetScript = channel.unary_unary(
                '/script.v1.ScriptService/GetScript',
                request_serializer=script_dot_v1_dot_script__pb2.GetScriptRequest.SerializeToString,
                response_deserializer=script_dot_v1_dot_script__pb2.Script.FromString,
                _registered_method=True)
        self.UpdateScript = channel.unary_unary(
                '/script.v1.ScriptService/UpdateScript',
                request_serializer=script_dot_v1_dot_script__pb2.UpdateScriptRequest.SerializeToString,
                response_deserializer=script_dot_v1_dot_script__pb2.Script.FromString,
                _registered_method=True)
        self.DeleteScript = channel.unary_unary(
                '/script.v1.ScriptService/DeleteScript',
                request_serializer=script_dot_v1_dot_script__pb2.DeleteScriptRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Error.FromString,
                _registered_method=True)
        self.ListScripts = channel.unary_unary(
                '/script.v1.ScriptService/ListScripts',
                request_serializer=script_dot_v1_dot_script__pb2.ListScriptsRequest.SerializeToString,
                response_deserializer=script_dot_v1_dot_script__pb2.ListScriptsResponse.FromString,
                _registered_method=True)
        self.GenerateScript = channel.unary_unary(
                '/script.v1.ScriptService/GenerateScript',
                request_serializer=script_dot_v1_dot_script__pb2.GenerateScriptRequest.SerializeToString,
                response_deserializer=script_dot_v1_dot_script__pb2.Script.FromString,
                _registered_method=True)
        self.PublishVersion = channel.unary_unary(
                '/script.v1.ScriptService/PublishVersion',
                request_serializer=script_dot_v1_dot_script__pb2.PublishVersionRequest.SerializeToString,
                response_deserializer=script_dot_v1_dot_script__pb2.Script.FromString,
                _registered_method=True)
        self.RollbackVersion = channel.unary_unary(
                '/script.v1.ScriptService/RollbackVersion',
                request_serializer=script_dot_v1_dot_script__pb2.RollbackVersionRequest.SerializeToString,
                response_deserializer=script_dot_v1_dot_script__pb2.Script.FromString,
                _registered_method=True)
        self.ListTemplates = channel.unary_unary(
                '/script.v1.ScriptService/ListTemplates',
                request_serializer=script_dot_v1_dot_script__pb2.ListTemplatesRequest.SerializeToString,
                response_deserializer=script_dot_v1_dot_script__pb2.ListTemplatesResponse.FromString,
                _registered_method=True)


class ScriptServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateScript(self, request, context):
        """── Script CRUD ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScripts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateScript(self, request, context):
        """── AI Generation ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishVersion(self, request, context):
        """── Version Management ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackVersion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTemplates(self, request, context):
        """── Templates ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScriptServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateScript': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateScript,
                    request_deserializer=script_dot_v1_dot_script__pb2.CreateScriptRequest.FromString,
                    response_serializer=script_dot_v1_dot_script__pb2.Script.SerializeToString,
            ),
            'GetScript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScript,
                    request_deserializer=script_dot_v1_dot_script__pb2.GetScriptRequest.FromString,
                    response_serializer=script_dot_v1_dot_script__pb2.Script.SerializeToString,
            ),
            'UpdateScript': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateScript,
                    request_deserializer=script_dot_v1_dot_script__pb2.UpdateScriptRequest.FromString,
                    response_serializer=script_dot_v1_dot_script__pb2.Script.SerializeToString,
            ),
            'DeleteScript': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteScript,
                    request_deserializer=script_dot_v1_dot_script__pb2.DeleteScriptRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Error.SerializeToString,
            ),
            'ListScripts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScripts,
                    request_deserializer=script_dot_v1_dot_script__pb2.ListScriptsRequest.FromString,
                    response_serializer=script_dot_v1_dot_script__pb2.ListScriptsResponse.SerializeToString,
            ),
            'GenerateScript': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateScript,
                    request_deserializer=script_dot_v1_dot_script__pb2.GenerateScriptRequest.FromString,
                    response_serializer=script_dot_v1_dot_script__pb2.Script.SerializeToString,
            ),
            'PublishVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishVersion,
                    request_deserializer=script_dot_v1_dot_script__pb2.PublishVersionRequest.FromString,
                    response_serializer=script_dot_v1_dot_script__pb2.Script.SerializeToString,
            ),
            'RollbackVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackVersion,
                    request_deserializer=script_dot_v1_dot_script__pb2.RollbackVersionRequest.FromString,
                    response_serializer=script_dot_v1_dot_script__pb2.Script.SerializeToString,
            ),
            'ListTemplates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTemplates,
                    request_deserializer=script_dot_v1_dot_script__pb2.ListTemplatesRequest.FromString,
                    response_serializer=script_dot_v1_dot_script__pb2.ListTemplatesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'script.v1.ScriptService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('script.v1.ScriptService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScriptService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/script.v1.ScriptService/CreateScript',
            script_dot_v1_dot_script__pb2.CreateScriptRequest.SerializeToString,
            script_dot_v1_dot_script__pb2.Script.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/script.v1.ScriptService/GetScript',
            script_dot_v1_dot_script__pb2.GetScriptRequest.SerializeToString,
            script_dot_v1_dot_script__pb2.Script.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/script.v1.ScriptService/UpdateScript',
            script_dot_v1_dot_script__pb2.UpdateScriptRequest.SerializeToString,
            script_dot_v1_dot_script__pb2.Script.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/script.v1.ScriptService/DeleteScript',
            script_dot_v1_dot_script__pb2.DeleteScriptRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScripts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/script.v1.ScriptService/ListScripts',
            script_dot_v1_dot_script__pb2.ListScriptsRequest.SerializeToString,
            script_dot_v1_dot_script__pb2.ListScriptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/script.v1.ScriptService/GenerateScript',
            script_dot_v1_dot_script__pb2.GenerateScriptRequest.SerializeToString,
            script_dot_v1_dot_script__pb2.Script.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/script.v1.ScriptService/PublishVersion',
            script_dot_v1_dot_script__pb2.PublishVersionRequest.SerializeToString,
            script_dot_v1_dot_script__pb2.Script.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/script.v1.ScriptService/RollbackVersion',
            script_dot_v1_dot_script__pb2.RollbackVersionRequest.SerializeToString,
            script_dot_v1_dot_script__pb2.Script.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTemplates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/script.v1.ScriptService/ListTemplates',
            script_dot_v1_dot_script__pb2.ListTemplatesRequest.SerializeToString,
            script_dot_v1_dot_script__pb2.ListTemplatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
