"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Script Service — AI Script Generation, Editing, Versioning, Templates"""

from collections import abc as _abc
from common.v1 import common_pb2 as _common_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ScriptStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ScriptStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ScriptStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SCRIPT_STATUS_UNSPECIFIED: _ScriptStatus.ValueType  # 0
    SCRIPT_STATUS_DRAFT: _ScriptStatus.ValueType  # 1
    SCRIPT_STATUS_PENDING_REVIEW: _ScriptStatus.ValueType  # 2
    SCRIPT_STATUS_APPROVED: _ScriptStatus.ValueType  # 3
    SCRIPT_STATUS_REJECTED: _ScriptStatus.ValueType  # 4
    SCRIPT_STATUS_ARCHIVED: _ScriptStatus.ValueType  # 5

class ScriptStatus(_ScriptStatus, metaclass=_ScriptStatusEnumTypeWrapper): ...

SCRIPT_STATUS_UNSPECIFIED: ScriptStatus.ValueType  # 0
SCRIPT_STATUS_DRAFT: ScriptStatus.ValueType  # 1
SCRIPT_STATUS_PENDING_REVIEW: ScriptStatus.ValueType  # 2
SCRIPT_STATUS_APPROVED: ScriptStatus.ValueType  # 3
SCRIPT_STATUS_REJECTED: ScriptStatus.ValueType  # 4
SCRIPT_STATUS_ARCHIVED: ScriptStatus.ValueType  # 5
Global___ScriptStatus: _TypeAlias = ScriptStatus  # noqa: Y015

class _ScriptStyle:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ScriptStyleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ScriptStyle.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SCRIPT_STYLE_UNSPECIFIED: _ScriptStyle.ValueType  # 0
    SCRIPT_STYLE_PASSIONATE: _ScriptStyle.ValueType  # 1
    """激情带货"""
    SCRIPT_STYLE_PROFESSIONAL: _ScriptStyle.ValueType  # 2
    """专业讲解"""
    SCRIPT_STYLE_STORY: _ScriptStyle.ValueType  # 3
    """故事营销"""
    SCRIPT_STYLE_COMPARISON: _ScriptStyle.ValueType  # 4
    """对比评测"""
    SCRIPT_STYLE_FLASH_SALE: _ScriptStyle.ValueType  # 5
    """限时秒杀"""

class ScriptStyle(_ScriptStyle, metaclass=_ScriptStyleEnumTypeWrapper): ...

SCRIPT_STYLE_UNSPECIFIED: ScriptStyle.ValueType  # 0
SCRIPT_STYLE_PASSIONATE: ScriptStyle.ValueType  # 1
"""激情带货"""
SCRIPT_STYLE_PROFESSIONAL: ScriptStyle.ValueType  # 2
"""专业讲解"""
SCRIPT_STYLE_STORY: ScriptStyle.ValueType  # 3
"""故事营销"""
SCRIPT_STYLE_COMPARISON: ScriptStyle.ValueType  # 4
"""对比评测"""
SCRIPT_STYLE_FLASH_SALE: ScriptStyle.ValueType  # 5
"""限时秒杀"""
Global___ScriptStyle: _TypeAlias = ScriptStyle  # noqa: Y015

class _SectionType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SectionTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SectionType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SECTION_TYPE_UNSPECIFIED: _SectionType.ValueType  # 0
    SECTION_TYPE_OPENING: _SectionType.ValueType  # 1
    SECTION_TYPE_PRODUCT_INTRO: _SectionType.ValueType  # 2
    SECTION_TYPE_FABRIC_DETAIL: _SectionType.ValueType  # 3
    SECTION_TYPE_SIZE_GUIDE: _SectionType.ValueType  # 4
    SECTION_TYPE_TRY_ON: _SectionType.ValueType  # 5
    SECTION_TYPE_PRICE_PROMO: _SectionType.ValueType  # 6
    SECTION_TYPE_CALL_TO_ACTION: _SectionType.ValueType  # 7
    SECTION_TYPE_CLOSING: _SectionType.ValueType  # 8
    SECTION_TYPE_QA: _SectionType.ValueType  # 9

class SectionType(_SectionType, metaclass=_SectionTypeEnumTypeWrapper): ...

SECTION_TYPE_UNSPECIFIED: SectionType.ValueType  # 0
SECTION_TYPE_OPENING: SectionType.ValueType  # 1
SECTION_TYPE_PRODUCT_INTRO: SectionType.ValueType  # 2
SECTION_TYPE_FABRIC_DETAIL: SectionType.ValueType  # 3
SECTION_TYPE_SIZE_GUIDE: SectionType.ValueType  # 4
SECTION_TYPE_TRY_ON: SectionType.ValueType  # 5
SECTION_TYPE_PRICE_PROMO: SectionType.ValueType  # 6
SECTION_TYPE_CALL_TO_ACTION: SectionType.ValueType  # 7
SECTION_TYPE_CLOSING: SectionType.ValueType  # 8
SECTION_TYPE_QA: SectionType.ValueType  # 9
Global___SectionType: _TypeAlias = SectionType  # noqa: Y015

@_typing.final
class Script(_message.Message):
    """── Script Entity ──"""

    DESCRIPTOR: _descriptor.Descriptor

    SCRIPT_ID_FIELD_NUMBER: _builtins.int
    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    STORE_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    INDUSTRY_FIELD_NUMBER: _builtins.int
    SECTIONS_FIELD_NUMBER: _builtins.int
    TOTAL_DURATION_ESTIMATE_MS_FIELD_NUMBER: _builtins.int
    AI_GENERATED_PROMPT_FIELD_NUMBER: _builtins.int
    AUDIT_INFO_FIELD_NUMBER: _builtins.int
    script_id: _builtins.str
    product_id: _builtins.str
    store_id: _builtins.str
    version: _builtins.int
    status: Global___ScriptStatus.ValueType
    style: Global___ScriptStyle.ValueType
    industry: _builtins.str
    total_duration_estimate_ms: _builtins.int
    ai_generated_prompt: _builtins.str
    @_builtins.property
    def sections(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScriptSection]: ...
    @_builtins.property
    def audit_info(self) -> _common_pb2.AuditInfo: ...
    def __init__(
        self,
        *,
        script_id: _builtins.str = ...,
        product_id: _builtins.str = ...,
        store_id: _builtins.str = ...,
        version: _builtins.int = ...,
        status: Global___ScriptStatus.ValueType = ...,
        style: Global___ScriptStyle.ValueType = ...,
        industry: _builtins.str = ...,
        sections: _abc.Iterable[Global___ScriptSection] | None = ...,
        total_duration_estimate_ms: _builtins.int = ...,
        ai_generated_prompt: _builtins.str = ...,
        audit_info: _common_pb2.AuditInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audit_info", b"audit_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ai_generated_prompt", b"ai_generated_prompt", "audit_info", b"audit_info", "industry", b"industry", "product_id", b"product_id", "script_id", b"script_id", "sections", b"sections", "status", b"status", "store_id", b"store_id", "style", b"style", "total_duration_estimate_ms", b"total_duration_estimate_ms", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Script: _TypeAlias = Script  # noqa: Y015

@_typing.final
class ScriptSection(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECTION_ID_FIELD_NUMBER: _builtins.int
    ORDER_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    TEXT_FIELD_NUMBER: _builtins.int
    DURATION_ESTIMATE_MS_FIELD_NUMBER: _builtins.int
    EMOTION_FIELD_NUMBER: _builtins.int
    ACTION_FIELD_NUMBER: _builtins.int
    SHOW_PRODUCT_CARD_FIELD_NUMBER: _builtins.int
    HIGHLIGHT_SELLING_POINT_FIELD_NUMBER: _builtins.int
    section_id: _builtins.str
    order: _builtins.int
    type: Global___SectionType.ValueType
    text: _builtins.str
    duration_estimate_ms: _builtins.int
    emotion: _builtins.str
    """neutral, happy, excited, warm, sad"""
    action: _builtins.str
    """wave_hand, point_product, show_detail, show_product_card"""
    show_product_card: _builtins.bool
    highlight_selling_point: _builtins.str
    def __init__(
        self,
        *,
        section_id: _builtins.str = ...,
        order: _builtins.int = ...,
        type: Global___SectionType.ValueType = ...,
        text: _builtins.str = ...,
        duration_estimate_ms: _builtins.int = ...,
        emotion: _builtins.str = ...,
        action: _builtins.str = ...,
        show_product_card: _builtins.bool = ...,
        highlight_selling_point: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action", b"action", "duration_estimate_ms", b"duration_estimate_ms", "emotion", b"emotion", "highlight_selling_point", b"highlight_selling_point", "order", b"order", "section_id", b"section_id", "show_product_card", b"show_product_card", "text", b"text", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScriptSection: _TypeAlias = ScriptSection  # noqa: Y015

@_typing.final
class CreateScriptRequest(_message.Message):
    """── CRUD ──"""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    STORE_ID_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    SECTIONS_FIELD_NUMBER: _builtins.int
    product_id: _builtins.str
    store_id: _builtins.str
    style: Global___ScriptStyle.ValueType
    @_builtins.property
    def sections(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScriptSection]: ...
    def __init__(
        self,
        *,
        product_id: _builtins.str = ...,
        store_id: _builtins.str = ...,
        style: Global___ScriptStyle.ValueType = ...,
        sections: _abc.Iterable[Global___ScriptSection] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product_id", b"product_id", "sections", b"sections", "store_id", b"store_id", "style", b"style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateScriptRequest: _TypeAlias = CreateScriptRequest  # noqa: Y015

@_typing.final
class GetScriptRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCRIPT_ID_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    script_id: _builtins.str
    version: _builtins.int
    def __init__(
        self,
        *,
        script_id: _builtins.str = ...,
        version: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_version", b"_version", "script_id", b"script_id", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__version: _TypeAlias = _typing.Literal["version"]  # noqa: Y015
    _WhichOneofArgType__version: _TypeAlias = _typing.Literal["_version", b"_version"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__version) -> _WhichOneofReturnType__version | None: ...

Global___GetScriptRequest: _TypeAlias = GetScriptRequest  # noqa: Y015

@_typing.final
class UpdateScriptRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCRIPT_ID_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    SECTIONS_FIELD_NUMBER: _builtins.int
    script_id: _builtins.str
    style: Global___ScriptStyle.ValueType
    @_builtins.property
    def sections(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScriptSection]: ...
    def __init__(
        self,
        *,
        script_id: _builtins.str = ...,
        style: Global___ScriptStyle.ValueType | None = ...,
        sections: _abc.Iterable[Global___ScriptSection] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_style", b"_style", "style", b"style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_style", b"_style", "script_id", b"script_id", "sections", b"sections", "style", b"style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__style: _TypeAlias = _typing.Literal["style"]  # noqa: Y015
    _WhichOneofArgType__style: _TypeAlias = _typing.Literal["_style", b"_style"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__style) -> _WhichOneofReturnType__style | None: ...

Global___UpdateScriptRequest: _TypeAlias = UpdateScriptRequest  # noqa: Y015

@_typing.final
class DeleteScriptRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCRIPT_ID_FIELD_NUMBER: _builtins.int
    script_id: _builtins.str
    def __init__(
        self,
        *,
        script_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["script_id", b"script_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteScriptRequest: _TypeAlias = DeleteScriptRequest  # noqa: Y015

@_typing.final
class ListScriptsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    status: Global___ScriptStatus.ValueType
    product_id: _builtins.str
    @_builtins.property
    def pagination(self) -> _common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        status: Global___ScriptStatus.ValueType | None = ...,
        product_id: _builtins.str | None = ...,
        pagination: _common_pb2.Pagination | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_product_id", b"_product_id", "_status", b"_status", "pagination", b"pagination", "product_id", b"product_id", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_product_id", b"_product_id", "_status", b"_status", "pagination", b"pagination", "product_id", b"product_id", "status", b"status", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__product_id: _TypeAlias = _typing.Literal["product_id"]  # noqa: Y015
    _WhichOneofArgType__product_id: _TypeAlias = _typing.Literal["_product_id", b"_product_id"]  # noqa: Y015
    _WhichOneofReturnType__status: _TypeAlias = _typing.Literal["status"]  # noqa: Y015
    _WhichOneofArgType__status: _TypeAlias = _typing.Literal["_status", b"_status"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__product_id) -> _WhichOneofReturnType__product_id | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status) -> _WhichOneofReturnType__status | None: ...

Global___ListScriptsRequest: _TypeAlias = ListScriptsRequest  # noqa: Y015

@_typing.final
class ListScriptsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCRIPTS_FIELD_NUMBER: _builtins.int
    PAGE_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def scripts(self) -> _containers.RepeatedCompositeFieldContainer[Global___Script]: ...
    @_builtins.property
    def page_info(self) -> _common_pb2.PageInfo: ...
    def __init__(
        self,
        *,
        scripts: _abc.Iterable[Global___Script] | None = ...,
        page_info: _common_pb2.PageInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info", "scripts", b"scripts"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListScriptsResponse: _TypeAlias = ListScriptsResponse  # noqa: Y015

@_typing.final
class GenerateScriptRequest(_message.Message):
    """── AI Generation ──"""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    TARGET_DURATION_SECONDS_FIELD_NUMBER: _builtins.int
    HIGHLIGHT_SELLING_POINTS_FIELD_NUMBER: _builtins.int
    EXTRA_CONTEXT_FIELD_NUMBER: _builtins.int
    product_id: _builtins.str
    style: Global___ScriptStyle.ValueType
    target_duration_seconds: _builtins.int
    """target 60-300"""
    extra_context: _builtins.str
    @_builtins.property
    def highlight_selling_points(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        product_id: _builtins.str = ...,
        style: Global___ScriptStyle.ValueType = ...,
        target_duration_seconds: _builtins.int = ...,
        highlight_selling_points: _abc.Iterable[_builtins.str] | None = ...,
        extra_context: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["extra_context", b"extra_context", "highlight_selling_points", b"highlight_selling_points", "product_id", b"product_id", "style", b"style", "target_duration_seconds", b"target_duration_seconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GenerateScriptRequest: _TypeAlias = GenerateScriptRequest  # noqa: Y015

@_typing.final
class PublishVersionRequest(_message.Message):
    """── Version ──"""

    DESCRIPTOR: _descriptor.Descriptor

    SCRIPT_ID_FIELD_NUMBER: _builtins.int
    NOTE_FIELD_NUMBER: _builtins.int
    script_id: _builtins.str
    note: _builtins.str
    def __init__(
        self,
        *,
        script_id: _builtins.str = ...,
        note: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["note", b"note", "script_id", b"script_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PublishVersionRequest: _TypeAlias = PublishVersionRequest  # noqa: Y015

@_typing.final
class RollbackVersionRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SCRIPT_ID_FIELD_NUMBER: _builtins.int
    TARGET_VERSION_FIELD_NUMBER: _builtins.int
    script_id: _builtins.str
    target_version: _builtins.int
    def __init__(
        self,
        *,
        script_id: _builtins.str = ...,
        target_version: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["script_id", b"script_id", "target_version", b"target_version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RollbackVersionRequest: _TypeAlias = RollbackVersionRequest  # noqa: Y015

@_typing.final
class ListTemplatesRequest(_message.Message):
    """── Template ──"""

    DESCRIPTOR: _descriptor.Descriptor

    INDUSTRY_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    industry: _builtins.str
    style: Global___ScriptStyle.ValueType
    def __init__(
        self,
        *,
        industry: _builtins.str | None = ...,
        style: Global___ScriptStyle.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_industry", b"_industry", "_style", b"_style", "industry", b"industry", "style", b"style"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_industry", b"_industry", "_style", b"_style", "industry", b"industry", "style", b"style"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__industry: _TypeAlias = _typing.Literal["industry"]  # noqa: Y015
    _WhichOneofArgType__industry: _TypeAlias = _typing.Literal["_industry", b"_industry"]  # noqa: Y015
    _WhichOneofReturnType__style: _TypeAlias = _typing.Literal["style"]  # noqa: Y015
    _WhichOneofArgType__style: _TypeAlias = _typing.Literal["_style", b"_style"]  # noqa: Y015
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__industry) -> _WhichOneofReturnType__industry | None: ...
    @_typing.overload
    def WhichOneof(self, oneof_group: _WhichOneofArgType__style) -> _WhichOneofReturnType__style | None: ...

Global___ListTemplatesRequest: _TypeAlias = ListTemplatesRequest  # noqa: Y015

@_typing.final
class ListTemplatesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEMPLATES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def templates(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScriptTemplate]: ...
    def __init__(
        self,
        *,
        templates: _abc.Iterable[Global___ScriptTemplate] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["templates", b"templates"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListTemplatesResponse: _TypeAlias = ListTemplatesResponse  # noqa: Y015

@_typing.final
class ScriptTemplate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEMPLATE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    INDUSTRY_FIELD_NUMBER: _builtins.int
    STYLE_FIELD_NUMBER: _builtins.int
    TEMPLATE_SECTIONS_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    template_id: _builtins.str
    name: _builtins.str
    industry: _builtins.str
    style: Global___ScriptStyle.ValueType
    description: _builtins.str
    @_builtins.property
    def template_sections(self) -> _containers.RepeatedCompositeFieldContainer[Global___ScriptSection]: ...
    def __init__(
        self,
        *,
        template_id: _builtins.str = ...,
        name: _builtins.str = ...,
        industry: _builtins.str = ...,
        style: Global___ScriptStyle.ValueType = ...,
        template_sections: _abc.Iterable[Global___ScriptSection] | None = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "industry", b"industry", "name", b"name", "style", b"style", "template_id", b"template_id", "template_sections", b"template_sections"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ScriptTemplate: _TypeAlias = ScriptTemplate  # noqa: Y015
