apiVersion: v1
kind: Service
metadata:
  name: analytics-svc
  namespace: livestream-tts
  labels:
    app: analytics-svc
spec:
  selector:
    app: analytics-svc
  ports:
    - name: http
      port: 8014
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc
  type: ClusterIP
