apiVersion: v1
kind: Service
metadata:
  name: platform-sync-svc
  namespace: livestream-tts
  labels:
    app: platform-sync-svc
spec:
  selector:
    app: platform-sync-svc
  ports:
    - name: http
      port: 8013
      targetPort: http
    - name: grpc
      port: 50051
      targetPort: grpc
  type: ClusterIP
