"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Stream Service — RTMP/SRT Push, Transcoding, Recording, HLS Packaging"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _StreamStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _StreamStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_StreamStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    STREAM_STATUS_UNSPECIFIED: _StreamStatus.ValueType  # 0
    STREAM_STATUS_CONNECTING: _StreamStatus.ValueType  # 1
    STREAM_STATUS_STREAMING: _StreamStatus.ValueType  # 2
    STREAM_STATUS_DISCONNECTED: _StreamStatus.ValueType  # 3
    STREAM_STATUS_ERROR: _StreamStatus.ValueType  # 4

class StreamStatus(_StreamStatus, metaclass=_StreamStatusEnumTypeWrapper): ...

STREAM_STATUS_UNSPECIFIED: StreamStatus.ValueType  # 0
STREAM_STATUS_CONNECTING: StreamStatus.ValueType  # 1
STREAM_STATUS_STREAMING: StreamStatus.ValueType  # 2
STREAM_STATUS_DISCONNECTED: StreamStatus.ValueType  # 3
STREAM_STATUS_ERROR: StreamStatus.ValueType  # 4
Global___StreamStatus: _TypeAlias = StreamStatus  # noqa: Y015

class _RecordingStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RecordingStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RecordingStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RECORDING_STATUS_UNSPECIFIED: _RecordingStatus.ValueType  # 0
    RECORDING_STATUS_RECORDING: _RecordingStatus.ValueType  # 1
    RECORDING_STATUS_COMPLETED: _RecordingStatus.ValueType  # 2
    RECORDING_STATUS_FAILED: _RecordingStatus.ValueType  # 3

class RecordingStatus(_RecordingStatus, metaclass=_RecordingStatusEnumTypeWrapper): ...

RECORDING_STATUS_UNSPECIFIED: RecordingStatus.ValueType  # 0
RECORDING_STATUS_RECORDING: RecordingStatus.ValueType  # 1
RECORDING_STATUS_COMPLETED: RecordingStatus.ValueType  # 2
RECORDING_STATUS_FAILED: RecordingStatus.ValueType  # 3
Global___RecordingStatus: _TypeAlias = RecordingStatus  # noqa: Y015

class _TranscodeStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TranscodeStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TranscodeStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TRANSCODE_STATUS_UNSPECIFIED: _TranscodeStatus.ValueType  # 0
    TRANSCODE_STATUS_QUEUED: _TranscodeStatus.ValueType  # 1
    TRANSCODE_STATUS_PROCESSING: _TranscodeStatus.ValueType  # 2
    TRANSCODE_STATUS_COMPLETED: _TranscodeStatus.ValueType  # 3
    TRANSCODE_STATUS_FAILED: _TranscodeStatus.ValueType  # 4

class TranscodeStatus(_TranscodeStatus, metaclass=_TranscodeStatusEnumTypeWrapper): ...

TRANSCODE_STATUS_UNSPECIFIED: TranscodeStatus.ValueType  # 0
TRANSCODE_STATUS_QUEUED: TranscodeStatus.ValueType  # 1
TRANSCODE_STATUS_PROCESSING: TranscodeStatus.ValueType  # 2
TRANSCODE_STATUS_COMPLETED: TranscodeStatus.ValueType  # 3
TRANSCODE_STATUS_FAILED: TranscodeStatus.ValueType  # 4
Global___TranscodeStatus: _TypeAlias = TranscodeStatus  # noqa: Y015

@_typing.final
class StreamSession(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    LIVE_ROOM_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    RTMP_URL_FIELD_NUMBER: _builtins.int
    STREAM_KEY_FIELD_NUMBER: _builtins.int
    PLATFORMS_FIELD_NUMBER: _builtins.int
    STARTED_AT_FIELD_NUMBER: _builtins.int
    BYTES_SENT_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    live_room_id: _builtins.str
    status: Global___StreamStatus.ValueType
    rtmp_url: _builtins.str
    stream_key: _builtins.str
    started_at: _builtins.int
    bytes_sent: _builtins.int
    @_builtins.property
    def platforms(self) -> _containers.RepeatedCompositeFieldContainer[Global___PlatformStream]: ...
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        live_room_id: _builtins.str = ...,
        status: Global___StreamStatus.ValueType = ...,
        rtmp_url: _builtins.str = ...,
        stream_key: _builtins.str = ...,
        platforms: _abc.Iterable[Global___PlatformStream] | None = ...,
        started_at: _builtins.int = ...,
        bytes_sent: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bytes_sent", b"bytes_sent", "live_room_id", b"live_room_id", "platforms", b"platforms", "rtmp_url", b"rtmp_url", "session_id", b"session_id", "started_at", b"started_at", "status", b"status", "stream_key", b"stream_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StreamSession: _TypeAlias = StreamSession  # noqa: Y015

@_typing.final
class PlatformStream(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PLATFORM_FIELD_NUMBER: _builtins.int
    RTMP_URL_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    platform: _builtins.str
    rtmp_url: _builtins.str
    status: Global___StreamStatus.ValueType
    def __init__(
        self,
        *,
        platform: _builtins.str = ...,
        rtmp_url: _builtins.str = ...,
        status: Global___StreamStatus.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["platform", b"platform", "rtmp_url", b"rtmp_url", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlatformStream: _TypeAlias = PlatformStream  # noqa: Y015

@_typing.final
class PushStatus(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    FPS_FIELD_NUMBER: _builtins.int
    BITRATE_KBPS_FIELD_NUMBER: _builtins.int
    UPTIME_SECONDS_FIELD_NUMBER: _builtins.int
    DROPPED_FRAMES_FIELD_NUMBER: _builtins.int
    HEALTH_SCORE_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    status: Global___StreamStatus.ValueType
    fps: _builtins.int
    bitrate_kbps: _builtins.int
    uptime_seconds: _builtins.int
    dropped_frames: _builtins.int
    health_score: _builtins.float
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
        status: Global___StreamStatus.ValueType = ...,
        fps: _builtins.int = ...,
        bitrate_kbps: _builtins.int = ...,
        uptime_seconds: _builtins.int = ...,
        dropped_frames: _builtins.int = ...,
        health_score: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bitrate_kbps", b"bitrate_kbps", "dropped_frames", b"dropped_frames", "fps", b"fps", "health_score", b"health_score", "session_id", b"session_id", "status", b"status", "uptime_seconds", b"uptime_seconds"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PushStatus: _TypeAlias = PushStatus  # noqa: Y015

@_typing.final
class Recording(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RECORDING_ID_FIELD_NUMBER: _builtins.int
    LIVE_ROOM_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    HLS_URL_FIELD_NUMBER: _builtins.int
    MP4_URL_FIELD_NUMBER: _builtins.int
    FILE_SIZE_BYTES_FIELD_NUMBER: _builtins.int
    DURATION_SECONDS_FIELD_NUMBER: _builtins.int
    STARTED_AT_FIELD_NUMBER: _builtins.int
    recording_id: _builtins.str
    live_room_id: _builtins.str
    status: Global___RecordingStatus.ValueType
    hls_url: _builtins.str
    mp4_url: _builtins.str
    file_size_bytes: _builtins.int
    duration_seconds: _builtins.int
    started_at: _builtins.int
    def __init__(
        self,
        *,
        recording_id: _builtins.str = ...,
        live_room_id: _builtins.str = ...,
        status: Global___RecordingStatus.ValueType = ...,
        hls_url: _builtins.str = ...,
        mp4_url: _builtins.str = ...,
        file_size_bytes: _builtins.int = ...,
        duration_seconds: _builtins.int = ...,
        started_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration_seconds", b"duration_seconds", "file_size_bytes", b"file_size_bytes", "hls_url", b"hls_url", "live_room_id", b"live_room_id", "mp4_url", b"mp4_url", "recording_id", b"recording_id", "started_at", b"started_at", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Recording: _TypeAlias = Recording  # noqa: Y015

@_typing.final
class TranscodeJob(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    INPUT_URL_FIELD_NUMBER: _builtins.int
    OUTPUT_URL_FIELD_NUMBER: _builtins.int
    PROGRESS_PERCENT_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    status: Global___TranscodeStatus.ValueType
    input_url: _builtins.str
    output_url: _builtins.str
    progress_percent: _builtins.int
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
        status: Global___TranscodeStatus.ValueType = ...,
        input_url: _builtins.str = ...,
        output_url: _builtins.str = ...,
        progress_percent: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["input_url", b"input_url", "job_id", b"job_id", "output_url", b"output_url", "progress_percent", b"progress_percent", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TranscodeJob: _TypeAlias = TranscodeJob  # noqa: Y015

@_typing.final
class StartPushRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIVE_ROOM_ID_FIELD_NUMBER: _builtins.int
    live_room_id: _builtins.str
    def __init__(
        self,
        *,
        live_room_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["live_room_id", b"live_room_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartPushRequest: _TypeAlias = StartPushRequest  # noqa: Y015

@_typing.final
class StopPushRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StopPushRequest: _TypeAlias = StopPushRequest  # noqa: Y015

@_typing.final
class GetPushStatusRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: _builtins.int
    session_id: _builtins.str
    def __init__(
        self,
        *,
        session_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["session_id", b"session_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetPushStatusRequest: _TypeAlias = GetPushStatusRequest  # noqa: Y015

@_typing.final
class StartRecordingRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    LIVE_ROOM_ID_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    live_room_id: _builtins.str
    format: _builtins.str
    def __init__(
        self,
        *,
        live_room_id: _builtins.str = ...,
        format: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["format", b"format", "live_room_id", b"live_room_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartRecordingRequest: _TypeAlias = StartRecordingRequest  # noqa: Y015

@_typing.final
class StopRecordingRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RECORDING_ID_FIELD_NUMBER: _builtins.int
    recording_id: _builtins.str
    def __init__(
        self,
        *,
        recording_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["recording_id", b"recording_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StopRecordingRequest: _TypeAlias = StopRecordingRequest  # noqa: Y015

@_typing.final
class TranscodeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class VideoConfig(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        WIDTH_FIELD_NUMBER: _builtins.int
        HEIGHT_FIELD_NUMBER: _builtins.int
        FPS_FIELD_NUMBER: _builtins.int
        BITRATE_KBPS_FIELD_NUMBER: _builtins.int
        FORMAT_FIELD_NUMBER: _builtins.int
        width: _builtins.int
        height: _builtins.int
        fps: _builtins.int
        bitrate_kbps: _builtins.int
        format: _builtins.str
        def __init__(
            self,
            *,
            width: _builtins.int = ...,
            height: _builtins.int = ...,
            fps: _builtins.int = ...,
            bitrate_kbps: _builtins.int = ...,
            format: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["bitrate_kbps", b"bitrate_kbps", "format", b"format", "fps", b"fps", "height", b"height", "width", b"width"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    RECORDING_ID_FIELD_NUMBER: _builtins.int
    TARGET_FIELD_NUMBER: _builtins.int
    recording_id: _builtins.str
    @_builtins.property
    def target(self) -> Global___TranscodeRequest.VideoConfig: ...
    def __init__(
        self,
        *,
        recording_id: _builtins.str = ...,
        target: Global___TranscodeRequest.VideoConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["target", b"target"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["recording_id", b"recording_id", "target", b"target"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TranscodeRequest: _TypeAlias = TranscodeRequest  # noqa: Y015

@_typing.final
class GetTranscodeJobRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_id", b"job_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetTranscodeJobRequest: _TypeAlias = GetTranscodeJobRequest  # noqa: Y015
