# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from stream.v1 import stream_pb2 as stream_dot_v1_dot_stream__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stream/v1/stream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartPush = channel.unary_unary(
                '/stream.v1.StreamService/StartPush',
                request_serializer=stream_dot_v1_dot_stream__pb2.StartPushRequest.SerializeToString,
                response_deserializer=stream_dot_v1_dot_stream__pb2.StreamSession.FromString,
                _registered_method=True)
        self.StopPush = channel.unary_unary(
                '/stream.v1.StreamService/StopPush',
                request_serializer=stream_dot_v1_dot_stream__pb2.StopPushRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Error.FromString,
                _registered_method=True)
        self.GetPushStatus = channel.unary_unary(
                '/stream.v1.StreamService/GetPushStatus',
                request_serializer=stream_dot_v1_dot_stream__pb2.GetPushStatusRequest.SerializeToString,
                response_deserializer=stream_dot_v1_dot_stream__pb2.PushStatus.FromString,
                _registered_method=True)
        self.StartRecording = channel.unary_unary(
                '/stream.v1.StreamService/StartRecording',
                request_serializer=stream_dot_v1_dot_stream__pb2.StartRecordingRequest.SerializeToString,
                response_deserializer=stream_dot_v1_dot_stream__pb2.Recording.FromString,
                _registered_method=True)
        self.StopRecording = channel.unary_unary(
                '/stream.v1.StreamService/StopRecording',
                request_serializer=stream_dot_v1_dot_stream__pb2.StopRecordingRequest.SerializeToString,
                response_deserializer=stream_dot_v1_dot_stream__pb2.Recording.FromString,
                _registered_method=True)
        self.Transcode = channel.unary_unary(
                '/stream.v1.StreamService/Transcode',
                request_serializer=stream_dot_v1_dot_stream__pb2.TranscodeRequest.SerializeToString,
                response_deserializer=stream_dot_v1_dot_stream__pb2.TranscodeJob.FromString,
                _registered_method=True)
        self.GetTranscodeJob = channel.unary_unary(
                '/stream.v1.StreamService/GetTranscodeJob',
                request_serializer=stream_dot_v1_dot_stream__pb2.GetTranscodeJobRequest.SerializeToString,
                response_deserializer=stream_dot_v1_dot_stream__pb2.TranscodeJob.FromString,
                _registered_method=True)


class StreamServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def StartPush(self, request, context):
        """── Push Stream ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPushStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRecording(self, request, context):
        """── Recording ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcode(self, request, context):
        """── Transcoding ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTranscodeJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartPush': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPush,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.StartPushRequest.FromString,
                    response_serializer=stream_dot_v1_dot_stream__pb2.StreamSession.SerializeToString,
            ),
            'StopPush': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPush,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.StopPushRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Error.SerializeToString,
            ),
            'GetPushStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPushStatus,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.GetPushStatusRequest.FromString,
                    response_serializer=stream_dot_v1_dot_stream__pb2.PushStatus.SerializeToString,
            ),
            'StartRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRecording,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.StartRecordingRequest.FromString,
                    response_serializer=stream_dot_v1_dot_stream__pb2.Recording.SerializeToString,
            ),
            'StopRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRecording,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.StopRecordingRequest.FromString,
                    response_serializer=stream_dot_v1_dot_stream__pb2.Recording.SerializeToString,
            ),
            'Transcode': grpc.unary_unary_rpc_method_handler(
                    servicer.Transcode,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.TranscodeRequest.FromString,
                    response_serializer=stream_dot_v1_dot_stream__pb2.TranscodeJob.SerializeToString,
            ),
            'GetTranscodeJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTranscodeJob,
                    request_deserializer=stream_dot_v1_dot_stream__pb2.GetTranscodeJobRequest.FromString,
                    response_serializer=stream_dot_v1_dot_stream__pb2.TranscodeJob.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stream.v1.StreamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stream.v1.StreamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream.v1.StreamService/StartPush',
            stream_dot_v1_dot_stream__pb2.StartPushRequest.SerializeToString,
            stream_dot_v1_dot_stream__pb2.StreamSession.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream.v1.StreamService/StopPush',
            stream_dot_v1_dot_stream__pb2.StopPushRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPushStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream.v1.StreamService/GetPushStatus',
            stream_dot_v1_dot_stream__pb2.GetPushStatusRequest.SerializeToString,
            stream_dot_v1_dot_stream__pb2.PushStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream.v1.StreamService/StartRecording',
            stream_dot_v1_dot_stream__pb2.StartRecordingRequest.SerializeToString,
            stream_dot_v1_dot_stream__pb2.Recording.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream.v1.StreamService/StopRecording',
            stream_dot_v1_dot_stream__pb2.StopRecordingRequest.SerializeToString,
            stream_dot_v1_dot_stream__pb2.Recording.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream.v1.StreamService/Transcode',
            stream_dot_v1_dot_stream__pb2.TranscodeRequest.SerializeToString,
            stream_dot_v1_dot_stream__pb2.TranscodeJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTranscodeJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stream.v1.StreamService/GetTranscodeJob',
            stream_dot_v1_dot_stream__pb2.GetTranscodeJobRequest.SerializeToString,
            stream_dot_v1_dot_stream__pb2.TranscodeJob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
