"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Knowledge Service — Knowledge Base, Document Parsing, Vector Retrieval (RAG)"""

from collections import abc as _abc
from common.v1 import common_pb2 as _common_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _KBStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _KBStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_KBStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    KB_STATUS_UNSPECIFIED: _KBStatus.ValueType  # 0
    KB_STATUS_ACTIVE: _KBStatus.ValueType  # 1
    KB_STATUS_BUILDING: _KBStatus.ValueType  # 2
    KB_STATUS_ERROR: _KBStatus.ValueType  # 3

class KBStatus(_KBStatus, metaclass=_KBStatusEnumTypeWrapper): ...

KB_STATUS_UNSPECIFIED: KBStatus.ValueType  # 0
KB_STATUS_ACTIVE: KBStatus.ValueType  # 1
KB_STATUS_BUILDING: KBStatus.ValueType  # 2
KB_STATUS_ERROR: KBStatus.ValueType  # 3
Global___KBStatus: _TypeAlias = KBStatus  # noqa: Y015

class _DocStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DocStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DocStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DOC_STATUS_UNSPECIFIED: _DocStatus.ValueType  # 0
    DOC_STATUS_UPLOADING: _DocStatus.ValueType  # 1
    DOC_STATUS_CHUNKING: _DocStatus.ValueType  # 2
    DOC_STATUS_EMBEDDING: _DocStatus.ValueType  # 3
    DOC_STATUS_READY: _DocStatus.ValueType  # 4
    DOC_STATUS_FAILED: _DocStatus.ValueType  # 5

class DocStatus(_DocStatus, metaclass=_DocStatusEnumTypeWrapper): ...

DOC_STATUS_UNSPECIFIED: DocStatus.ValueType  # 0
DOC_STATUS_UPLOADING: DocStatus.ValueType  # 1
DOC_STATUS_CHUNKING: DocStatus.ValueType  # 2
DOC_STATUS_EMBEDDING: DocStatus.ValueType  # 3
DOC_STATUS_READY: DocStatus.ValueType  # 4
DOC_STATUS_FAILED: DocStatus.ValueType  # 5
Global___DocStatus: _TypeAlias = DocStatus  # noqa: Y015

@_typing.final
class KnowledgeBase(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KB_ID_FIELD_NUMBER: _builtins.int
    STORE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    INDUSTRY_FIELD_NUMBER: _builtins.int
    DOCUMENT_COUNT_FIELD_NUMBER: _builtins.int
    FAQ_COUNT_FIELD_NUMBER: _builtins.int
    TOTAL_CHUNKS_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    AUDIT_INFO_FIELD_NUMBER: _builtins.int
    kb_id: _builtins.str
    store_id: _builtins.str
    name: _builtins.str
    description: _builtins.str
    industry: _builtins.str
    document_count: _builtins.int
    faq_count: _builtins.int
    total_chunks: _builtins.int
    status: Global___KBStatus.ValueType
    @_builtins.property
    def audit_info(self) -> _common_pb2.AuditInfo: ...
    def __init__(
        self,
        *,
        kb_id: _builtins.str = ...,
        store_id: _builtins.str = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        industry: _builtins.str = ...,
        document_count: _builtins.int = ...,
        faq_count: _builtins.int = ...,
        total_chunks: _builtins.int = ...,
        status: Global___KBStatus.ValueType = ...,
        audit_info: _common_pb2.AuditInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audit_info", b"audit_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audit_info", b"audit_info", "description", b"description", "document_count", b"document_count", "faq_count", b"faq_count", "industry", b"industry", "kb_id", b"kb_id", "name", b"name", "status", b"status", "store_id", b"store_id", "total_chunks", b"total_chunks"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___KnowledgeBase: _TypeAlias = KnowledgeBase  # noqa: Y015

@_typing.final
class Document(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DOC_ID_FIELD_NUMBER: _builtins.int
    KB_ID_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    FILE_TYPE_FIELD_NUMBER: _builtins.int
    FILE_SIZE_BYTES_FIELD_NUMBER: _builtins.int
    CHUNK_COUNT_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    AUDIT_INFO_FIELD_NUMBER: _builtins.int
    doc_id: _builtins.str
    kb_id: _builtins.str
    filename: _builtins.str
    file_type: _builtins.str
    file_size_bytes: _builtins.int
    chunk_count: _builtins.int
    status: Global___DocStatus.ValueType
    @_builtins.property
    def audit_info(self) -> _common_pb2.AuditInfo: ...
    def __init__(
        self,
        *,
        doc_id: _builtins.str = ...,
        kb_id: _builtins.str = ...,
        filename: _builtins.str = ...,
        file_type: _builtins.str = ...,
        file_size_bytes: _builtins.int = ...,
        chunk_count: _builtins.int = ...,
        status: Global___DocStatus.ValueType = ...,
        audit_info: _common_pb2.AuditInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audit_info", b"audit_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audit_info", b"audit_info", "chunk_count", b"chunk_count", "doc_id", b"doc_id", "file_size_bytes", b"file_size_bytes", "file_type", b"file_type", "filename", b"filename", "kb_id", b"kb_id", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Document: _TypeAlias = Document  # noqa: Y015

@_typing.final
class FAQ(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FAQ_ID_FIELD_NUMBER: _builtins.int
    KB_ID_FIELD_NUMBER: _builtins.int
    QUESTION_FIELD_NUMBER: _builtins.int
    ANSWER_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    AUDIT_INFO_FIELD_NUMBER: _builtins.int
    faq_id: _builtins.str
    kb_id: _builtins.str
    question: _builtins.str
    answer: _builtins.str
    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def audit_info(self) -> _common_pb2.AuditInfo: ...
    def __init__(
        self,
        *,
        faq_id: _builtins.str = ...,
        kb_id: _builtins.str = ...,
        question: _builtins.str = ...,
        answer: _builtins.str = ...,
        tags: _abc.Iterable[_builtins.str] | None = ...,
        audit_info: _common_pb2.AuditInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audit_info", b"audit_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["answer", b"answer", "audit_info", b"audit_info", "faq_id", b"faq_id", "kb_id", b"kb_id", "question", b"question", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FAQ: _TypeAlias = FAQ  # noqa: Y015

@_typing.final
class SearchRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KB_ID_FIELD_NUMBER: _builtins.int
    QUERY_FIELD_NUMBER: _builtins.int
    TOP_K_FIELD_NUMBER: _builtins.int
    MIN_SCORE_FIELD_NUMBER: _builtins.int
    kb_id: _builtins.str
    query: _builtins.str
    top_k: _builtins.int
    min_score: _builtins.float
    def __init__(
        self,
        *,
        kb_id: _builtins.str = ...,
        query: _builtins.str = ...,
        top_k: _builtins.int = ...,
        min_score: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kb_id", b"kb_id", "min_score", b"min_score", "query", b"query", "top_k", b"top_k"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchRequest: _TypeAlias = SearchRequest  # noqa: Y015

@_typing.final
class SearchResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    RETRIEVAL_MS_FIELD_NUMBER: _builtins.int
    retrieval_ms: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___SearchResult]: ...
    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___SearchResult] | None = ...,
        retrieval_ms: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results", "retrieval_ms", b"retrieval_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchResponse: _TypeAlias = SearchResponse  # noqa: Y015

@_typing.final
class SearchResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_ID_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    SCORE_FIELD_NUMBER: _builtins.int
    SOURCE_DOC_ID_FIELD_NUMBER: _builtins.int
    SOURCE_FILENAME_FIELD_NUMBER: _builtins.int
    chunk_id: _builtins.str
    content: _builtins.str
    score: _builtins.float
    source_doc_id: _builtins.str
    source_filename: _builtins.str
    def __init__(
        self,
        *,
        chunk_id: _builtins.str = ...,
        content: _builtins.str = ...,
        score: _builtins.float = ...,
        source_doc_id: _builtins.str = ...,
        source_filename: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk_id", b"chunk_id", "content", b"content", "score", b"score", "source_doc_id", b"source_doc_id", "source_filename", b"source_filename"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SearchResult: _TypeAlias = SearchResult  # noqa: Y015

@_typing.final
class CreateKBRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    INDUSTRY_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    name: _builtins.str
    description: _builtins.str
    industry: _builtins.str
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        name: _builtins.str = ...,
        description: _builtins.str = ...,
        industry: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["description", b"description", "industry", b"industry", "name", b"name", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateKBRequest: _TypeAlias = CreateKBRequest  # noqa: Y015

@_typing.final
class GetKBRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KB_ID_FIELD_NUMBER: _builtins.int
    kb_id: _builtins.str
    def __init__(
        self,
        *,
        kb_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kb_id", b"kb_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetKBRequest: _TypeAlias = GetKBRequest  # noqa: Y015

@_typing.final
class DeleteKBRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KB_ID_FIELD_NUMBER: _builtins.int
    kb_id: _builtins.str
    def __init__(
        self,
        *,
        kb_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kb_id", b"kb_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteKBRequest: _TypeAlias = DeleteKBRequest  # noqa: Y015

@_typing.final
class ListKBsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    @_builtins.property
    def pagination(self) -> _common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        pagination: _common_pb2.Pagination | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListKBsRequest: _TypeAlias = ListKBsRequest  # noqa: Y015

@_typing.final
class ListKBsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KBS_FIELD_NUMBER: _builtins.int
    PAGE_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def kbs(self) -> _containers.RepeatedCompositeFieldContainer[Global___KnowledgeBase]: ...
    @_builtins.property
    def page_info(self) -> _common_pb2.PageInfo: ...
    def __init__(
        self,
        *,
        kbs: _abc.Iterable[Global___KnowledgeBase] | None = ...,
        page_info: _common_pb2.PageInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kbs", b"kbs", "page_info", b"page_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListKBsResponse: _TypeAlias = ListKBsResponse  # noqa: Y015

@_typing.final
class UploadDocumentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KB_ID_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    CONTENT_FIELD_NUMBER: _builtins.int
    kb_id: _builtins.str
    filename: _builtins.str
    content: _builtins.bytes
    def __init__(
        self,
        *,
        kb_id: _builtins.str = ...,
        filename: _builtins.str = ...,
        content: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["content", b"content", "filename", b"filename", "kb_id", b"kb_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UploadDocumentRequest: _TypeAlias = UploadDocumentRequest  # noqa: Y015

@_typing.final
class DeleteDocumentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DOC_ID_FIELD_NUMBER: _builtins.int
    doc_id: _builtins.str
    def __init__(
        self,
        *,
        doc_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["doc_id", b"doc_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteDocumentRequest: _TypeAlias = DeleteDocumentRequest  # noqa: Y015

@_typing.final
class CreateFAQRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KB_ID_FIELD_NUMBER: _builtins.int
    QUESTION_FIELD_NUMBER: _builtins.int
    ANSWER_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    kb_id: _builtins.str
    question: _builtins.str
    answer: _builtins.str
    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        kb_id: _builtins.str = ...,
        question: _builtins.str = ...,
        answer: _builtins.str = ...,
        tags: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["answer", b"answer", "kb_id", b"kb_id", "question", b"question", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CreateFAQRequest: _TypeAlias = CreateFAQRequest  # noqa: Y015

@_typing.final
class DeleteFAQRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FAQ_ID_FIELD_NUMBER: _builtins.int
    faq_id: _builtins.str
    def __init__(
        self,
        *,
        faq_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["faq_id", b"faq_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeleteFAQRequest: _TypeAlias = DeleteFAQRequest  # noqa: Y015

@_typing.final
class ListFAQsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KB_ID_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    kb_id: _builtins.str
    @_builtins.property
    def pagination(self) -> _common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        kb_id: _builtins.str = ...,
        pagination: _common_pb2.Pagination | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pagination", b"pagination"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kb_id", b"kb_id", "pagination", b"pagination"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListFAQsRequest: _TypeAlias = ListFAQsRequest  # noqa: Y015

@_typing.final
class ListFAQsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FAQS_FIELD_NUMBER: _builtins.int
    PAGE_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def faqs(self) -> _containers.RepeatedCompositeFieldContainer[Global___FAQ]: ...
    @_builtins.property
    def page_info(self) -> _common_pb2.PageInfo: ...
    def __init__(
        self,
        *,
        faqs: _abc.Iterable[Global___FAQ] | None = ...,
        page_info: _common_pb2.PageInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["faqs", b"faqs", "page_info", b"page_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListFAQsResponse: _TypeAlias = ListFAQsResponse  # noqa: Y015
