apiVersion: v1
kind: Service
metadata:
  name: tts-svc
  labels:
    app: tts-svc
spec:
  type: ClusterIP
  selector:
    app: tts-svc
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
      protocol: TCP
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: tts-svc-headless
  labels:
    app: tts-svc
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: tts-svc
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: http
      port: 8080
      targetPort: 8080
