# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from product.v1 import product_pb2 as product_dot_v1_dot_product__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in product/v1/product_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProduct = channel.unary_unary(
                '/product.v1.ProductService/CreateProduct',
                request_serializer=product_dot_v1_dot_product__pb2.CreateProductRequest.SerializeToString,
                response_deserializer=product_dot_v1_dot_product__pb2.Product.FromString,
                _registered_method=True)
        self.GetProduct = channel.unary_unary(
                '/product.v1.ProductService/GetProduct',
                request_serializer=product_dot_v1_dot_product__pb2.GetProductRequest.SerializeToString,
                response_deserializer=product_dot_v1_dot_product__pb2.Product.FromString,
                _registered_method=True)
        self.UpdateProduct = channel.unary_unary(
                '/product.v1.ProductService/UpdateProduct',
                request_serializer=product_dot_v1_dot_product__pb2.UpdateProductRequest.SerializeToString,
                response_deserializer=product_dot_v1_dot_product__pb2.Product.FromString,
                _registered_method=True)
        self.DeleteProduct = channel.unary_unary(
                '/product.v1.ProductService/DeleteProduct',
                request_serializer=product_dot_v1_dot_product__pb2.DeleteProductRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Error.FromString,
                _registered_method=True)
        self.ListProducts = channel.unary_unary(
                '/product.v1.ProductService/ListProducts',
                request_serializer=product_dot_v1_dot_product__pb2.ListProductsRequest.SerializeToString,
                response_deserializer=product_dot_v1_dot_product__pb2.ListProductsResponse.FromString,
                _registered_method=True)
        self.AddSku = channel.unary_unary(
                '/product.v1.ProductService/AddSku',
                request_serializer=product_dot_v1_dot_product__pb2.AddSkuRequest.SerializeToString,
                response_deserializer=product_dot_v1_dot_product__pb2.Product.FromString,
                _registered_method=True)
        self.UpdateSku = channel.unary_unary(
                '/product.v1.ProductService/UpdateSku',
                request_serializer=product_dot_v1_dot_product__pb2.UpdateSkuRequest.SerializeToString,
                response_deserializer=product_dot_v1_dot_product__pb2.Product.FromString,
                _registered_method=True)
        self.DeleteSku = channel.unary_unary(
                '/product.v1.ProductService/DeleteSku',
                request_serializer=product_dot_v1_dot_product__pb2.DeleteSkuRequest.SerializeToString,
                response_deserializer=product_dot_v1_dot_product__pb2.Product.FromString,
                _registered_method=True)
        self.ListCategories = channel.unary_unary(
                '/product.v1.ProductService/ListCategories',
                request_serializer=product_dot_v1_dot_product__pb2.ListCategoriesRequest.SerializeToString,
                response_deserializer=product_dot_v1_dot_product__pb2.ListCategoriesResponse.FromString,
                _registered_method=True)
        self.ImportProducts = channel.unary_unary(
                '/product.v1.ProductService/ImportProducts',
                request_serializer=product_dot_v1_dot_product__pb2.ImportProductsRequest.SerializeToString,
                response_deserializer=product_dot_v1_dot_product__pb2.ImportProductsResponse.FromString,
                _registered_method=True)
        self.GetPlatformSyncStatus = channel.unary_unary(
                '/product.v1.ProductService/GetPlatformSyncStatus',
                request_serializer=product_dot_v1_dot_product__pb2.GetPlatformSyncStatusRequest.SerializeToString,
                response_deserializer=product_dot_v1_dot_product__pb2.PlatformSyncStatus.FromString,
                _registered_method=True)


class ProductServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateProduct(self, request, context):
        """── Product CRUD ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProducts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddSku(self, request, context):
        """── SKU Management ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSku(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSku(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCategories(self, request, context):
        """── Category ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportProducts(self, request, context):
        """── Import / Export ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlatformSyncStatus(self, request, context):
        """── Platform Sync Status ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProduct,
                    request_deserializer=product_dot_v1_dot_product__pb2.CreateProductRequest.FromString,
                    response_serializer=product_dot_v1_dot_product__pb2.Product.SerializeToString,
            ),
            'GetProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProduct,
                    request_deserializer=product_dot_v1_dot_product__pb2.GetProductRequest.FromString,
                    response_serializer=product_dot_v1_dot_product__pb2.Product.SerializeToString,
            ),
            'UpdateProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProduct,
                    request_deserializer=product_dot_v1_dot_product__pb2.UpdateProductRequest.FromString,
                    response_serializer=product_dot_v1_dot_product__pb2.Product.SerializeToString,
            ),
            'DeleteProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProduct,
                    request_deserializer=product_dot_v1_dot_product__pb2.DeleteProductRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Error.SerializeToString,
            ),
            'ListProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProducts,
                    request_deserializer=product_dot_v1_dot_product__pb2.ListProductsRequest.FromString,
                    response_serializer=product_dot_v1_dot_product__pb2.ListProductsResponse.SerializeToString,
            ),
            'AddSku': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSku,
                    request_deserializer=product_dot_v1_dot_product__pb2.AddSkuRequest.FromString,
                    response_serializer=product_dot_v1_dot_product__pb2.Product.SerializeToString,
            ),
            'UpdateSku': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSku,
                    request_deserializer=product_dot_v1_dot_product__pb2.UpdateSkuRequest.FromString,
                    response_serializer=product_dot_v1_dot_product__pb2.Product.SerializeToString,
            ),
            'DeleteSku': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSku,
                    request_deserializer=product_dot_v1_dot_product__pb2.DeleteSkuRequest.FromString,
                    response_serializer=product_dot_v1_dot_product__pb2.Product.SerializeToString,
            ),
            'ListCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCategories,
                    request_deserializer=product_dot_v1_dot_product__pb2.ListCategoriesRequest.FromString,
                    response_serializer=product_dot_v1_dot_product__pb2.ListCategoriesResponse.SerializeToString,
            ),
            'ImportProducts': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportProducts,
                    request_deserializer=product_dot_v1_dot_product__pb2.ImportProductsRequest.FromString,
                    response_serializer=product_dot_v1_dot_product__pb2.ImportProductsResponse.SerializeToString,
            ),
            'GetPlatformSyncStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlatformSyncStatus,
                    request_deserializer=product_dot_v1_dot_product__pb2.GetPlatformSyncStatusRequest.FromString,
                    response_serializer=product_dot_v1_dot_product__pb2.PlatformSyncStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'product.v1.ProductService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('product.v1.ProductService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/CreateProduct',
            product_dot_v1_dot_product__pb2.CreateProductRequest.SerializeToString,
            product_dot_v1_dot_product__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/GetProduct',
            product_dot_v1_dot_product__pb2.GetProductRequest.SerializeToString,
            product_dot_v1_dot_product__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/UpdateProduct',
            product_dot_v1_dot_product__pb2.UpdateProductRequest.SerializeToString,
            product_dot_v1_dot_product__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/DeleteProduct',
            product_dot_v1_dot_product__pb2.DeleteProductRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/ListProducts',
            product_dot_v1_dot_product__pb2.ListProductsRequest.SerializeToString,
            product_dot_v1_dot_product__pb2.ListProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddSku(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/AddSku',
            product_dot_v1_dot_product__pb2.AddSkuRequest.SerializeToString,
            product_dot_v1_dot_product__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSku(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/UpdateSku',
            product_dot_v1_dot_product__pb2.UpdateSkuRequest.SerializeToString,
            product_dot_v1_dot_product__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSku(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/DeleteSku',
            product_dot_v1_dot_product__pb2.DeleteSkuRequest.SerializeToString,
            product_dot_v1_dot_product__pb2.Product.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/ListCategories',
            product_dot_v1_dot_product__pb2.ListCategoriesRequest.SerializeToString,
            product_dot_v1_dot_product__pb2.ListCategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportProducts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/ImportProducts',
            product_dot_v1_dot_product__pb2.ImportProductsRequest.SerializeToString,
            product_dot_v1_dot_product__pb2.ImportProductsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlatformSyncStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/product.v1.ProductService/GetPlatformSyncStatus',
            product_dot_v1_dot_product__pb2.GetPlatformSyncStatusRequest.SerializeToString,
            product_dot_v1_dot_product__pb2.PlatformSyncStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
