"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Platform Sync Service — Multi-Platform Product & Order Sync"""

from collections import abc as _abc
from common.v1 import common_pb2 as _common_pb2
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _Platform:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PlatformEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Platform.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PLATFORM_UNSPECIFIED: _Platform.ValueType  # 0
    PLATFORM_TAOBAO: _Platform.ValueType  # 1
    PLATFORM_DOUYIN: _Platform.ValueType  # 2
    PLATFORM_JD: _Platform.ValueType  # 3
    PLATFORM_KUAISHOU: _Platform.ValueType  # 4
    PLATFORM_PINDUODUO: _Platform.ValueType  # 5

class Platform(_Platform, metaclass=_PlatformEnumTypeWrapper):
    """── Platform ──"""

PLATFORM_UNSPECIFIED: Platform.ValueType  # 0
PLATFORM_TAOBAO: Platform.ValueType  # 1
PLATFORM_DOUYIN: Platform.ValueType  # 2
PLATFORM_JD: Platform.ValueType  # 3
PLATFORM_KUAISHOU: Platform.ValueType  # 4
PLATFORM_PINDUODUO: Platform.ValueType  # 5
Global___Platform: _TypeAlias = Platform  # noqa: Y015

class _BindingStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _BindingStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_BindingStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    BINDING_STATUS_UNSPECIFIED: _BindingStatus.ValueType  # 0
    BINDING_STATUS_ACTIVE: _BindingStatus.ValueType  # 1
    BINDING_STATUS_EXPIRED: _BindingStatus.ValueType  # 2
    BINDING_STATUS_REVOKED: _BindingStatus.ValueType  # 3

class BindingStatus(_BindingStatus, metaclass=_BindingStatusEnumTypeWrapper): ...

BINDING_STATUS_UNSPECIFIED: BindingStatus.ValueType  # 0
BINDING_STATUS_ACTIVE: BindingStatus.ValueType  # 1
BINDING_STATUS_EXPIRED: BindingStatus.ValueType  # 2
BINDING_STATUS_REVOKED: BindingStatus.ValueType  # 3
Global___BindingStatus: _TypeAlias = BindingStatus  # noqa: Y015

class _SyncDirection:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SyncDirectionEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SyncDirection.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SYNC_DIRECTION_UNSPECIFIED: _SyncDirection.ValueType  # 0
    SYNC_DIRECTION_PUSH: _SyncDirection.ValueType  # 1
    """推送至平台"""
    SYNC_DIRECTION_PULL: _SyncDirection.ValueType  # 2
    """从平台拉取"""

class SyncDirection(_SyncDirection, metaclass=_SyncDirectionEnumTypeWrapper): ...

SYNC_DIRECTION_UNSPECIFIED: SyncDirection.ValueType  # 0
SYNC_DIRECTION_PUSH: SyncDirection.ValueType  # 1
"""推送至平台"""
SYNC_DIRECTION_PULL: SyncDirection.ValueType  # 2
"""从平台拉取"""
Global___SyncDirection: _TypeAlias = SyncDirection  # noqa: Y015

class _SyncJobStatus:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SyncJobStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SyncJobStatus.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SYNC_JOB_STATUS_UNSPECIFIED: _SyncJobStatus.ValueType  # 0
    SYNC_JOB_STATUS_PENDING: _SyncJobStatus.ValueType  # 1
    SYNC_JOB_STATUS_IN_PROGRESS: _SyncJobStatus.ValueType  # 2
    SYNC_JOB_STATUS_SUCCESS: _SyncJobStatus.ValueType  # 3
    SYNC_JOB_STATUS_FAILED: _SyncJobStatus.ValueType  # 4

class SyncJobStatus(_SyncJobStatus, metaclass=_SyncJobStatusEnumTypeWrapper): ...

SYNC_JOB_STATUS_UNSPECIFIED: SyncJobStatus.ValueType  # 0
SYNC_JOB_STATUS_PENDING: SyncJobStatus.ValueType  # 1
SYNC_JOB_STATUS_IN_PROGRESS: SyncJobStatus.ValueType  # 2
SYNC_JOB_STATUS_SUCCESS: SyncJobStatus.ValueType  # 3
SYNC_JOB_STATUS_FAILED: SyncJobStatus.ValueType  # 4
Global___SyncJobStatus: _TypeAlias = SyncJobStatus  # noqa: Y015

@_typing.final
class PlatformStoreBinding(_message.Message):
    """── Store Binding ──"""

    DESCRIPTOR: _descriptor.Descriptor

    BINDING_ID_FIELD_NUMBER: _builtins.int
    STORE_ID_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    PLATFORM_STORE_ID_FIELD_NUMBER: _builtins.int
    PLATFORM_STORE_NAME_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    ACCESS_TOKEN_ENCRYPTED_FIELD_NUMBER: _builtins.int
    TOKEN_EXPIRES_AT_FIELD_NUMBER: _builtins.int
    BOUND_AT_FIELD_NUMBER: _builtins.int
    binding_id: _builtins.str
    store_id: _builtins.str
    platform: Global___Platform.ValueType
    platform_store_id: _builtins.str
    platform_store_name: _builtins.str
    status: Global___BindingStatus.ValueType
    access_token_encrypted: _builtins.str
    token_expires_at: _builtins.int
    bound_at: _builtins.int
    def __init__(
        self,
        *,
        binding_id: _builtins.str = ...,
        store_id: _builtins.str = ...,
        platform: Global___Platform.ValueType = ...,
        platform_store_id: _builtins.str = ...,
        platform_store_name: _builtins.str = ...,
        status: Global___BindingStatus.ValueType = ...,
        access_token_encrypted: _builtins.str = ...,
        token_expires_at: _builtins.int = ...,
        bound_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["access_token_encrypted", b"access_token_encrypted", "binding_id", b"binding_id", "bound_at", b"bound_at", "platform", b"platform", "platform_store_id", b"platform_store_id", "platform_store_name", b"platform_store_name", "status", b"status", "store_id", b"store_id", "token_expires_at", b"token_expires_at"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PlatformStoreBinding: _TypeAlias = PlatformStoreBinding  # noqa: Y015

@_typing.final
class BindPlatformStoreRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    AUTH_CODE_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    platform: Global___Platform.ValueType
    auth_code: _builtins.str
    """OAuth authorization code"""
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        platform: Global___Platform.ValueType = ...,
        auth_code: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth_code", b"auth_code", "platform", b"platform", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BindPlatformStoreRequest: _TypeAlias = BindPlatformStoreRequest  # noqa: Y015

@_typing.final
class UnbindPlatformStoreRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINDING_ID_FIELD_NUMBER: _builtins.int
    binding_id: _builtins.str
    def __init__(
        self,
        *,
        binding_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["binding_id", b"binding_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___UnbindPlatformStoreRequest: _TypeAlias = UnbindPlatformStoreRequest  # noqa: Y015

@_typing.final
class ListBindingsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListBindingsRequest: _TypeAlias = ListBindingsRequest  # noqa: Y015

@_typing.final
class ListBindingsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BINDINGS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bindings(self) -> _containers.RepeatedCompositeFieldContainer[Global___PlatformStoreBinding]: ...
    def __init__(
        self,
        *,
        bindings: _abc.Iterable[Global___PlatformStoreBinding] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bindings", b"bindings"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListBindingsResponse: _TypeAlias = ListBindingsResponse  # noqa: Y015

@_typing.final
class SyncProductRequest(_message.Message):
    """── Sync ──"""

    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    TARGET_PLATFORM_FIELD_NUMBER: _builtins.int
    DIRECTION_FIELD_NUMBER: _builtins.int
    product_id: _builtins.str
    target_platform: Global___Platform.ValueType
    direction: Global___SyncDirection.ValueType
    def __init__(
        self,
        *,
        product_id: _builtins.str = ...,
        target_platform: Global___Platform.ValueType = ...,
        direction: Global___SyncDirection.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["direction", b"direction", "product_id", b"product_id", "target_platform", b"target_platform"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SyncProductRequest: _TypeAlias = SyncProductRequest  # noqa: Y015

@_typing.final
class BulkSyncProductsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PRODUCT_IDS_FIELD_NUMBER: _builtins.int
    TARGET_PLATFORMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def product_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def target_platforms(self) -> _containers.RepeatedScalarFieldContainer[Global___Platform.ValueType]: ...
    def __init__(
        self,
        *,
        product_ids: _abc.Iterable[_builtins.str] | None = ...,
        target_platforms: _abc.Iterable[Global___Platform.ValueType] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["product_ids", b"product_ids", "target_platforms", b"target_platforms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BulkSyncProductsRequest: _TypeAlias = BulkSyncProductsRequest  # noqa: Y015

@_typing.final
class BulkSyncResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOBS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def jobs(self) -> _containers.RepeatedCompositeFieldContainer[Global___SyncJob]: ...
    def __init__(
        self,
        *,
        jobs: _abc.Iterable[Global___SyncJob] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["jobs", b"jobs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BulkSyncResponse: _TypeAlias = BulkSyncResponse  # noqa: Y015

@_typing.final
class SyncJob(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    PRODUCT_ID_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    PLATFORM_PRODUCT_ID_FIELD_NUMBER: _builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: _builtins.int
    RETRY_COUNT_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    COMPLETED_AT_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    product_id: _builtins.str
    platform: Global___Platform.ValueType
    status: Global___SyncJobStatus.ValueType
    platform_product_id: _builtins.str
    error_message: _builtins.str
    retry_count: _builtins.int
    created_at: _builtins.int
    completed_at: _builtins.int
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
        product_id: _builtins.str = ...,
        platform: Global___Platform.ValueType = ...,
        status: Global___SyncJobStatus.ValueType = ...,
        platform_product_id: _builtins.str = ...,
        error_message: _builtins.str = ...,
        retry_count: _builtins.int = ...,
        created_at: _builtins.int = ...,
        completed_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["completed_at", b"completed_at", "created_at", b"created_at", "error_message", b"error_message", "job_id", b"job_id", "platform", b"platform", "platform_product_id", b"platform_product_id", "product_id", b"product_id", "retry_count", b"retry_count", "status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SyncJob: _TypeAlias = SyncJob  # noqa: Y015

@_typing.final
class GetSyncJobRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOB_ID_FIELD_NUMBER: _builtins.int
    job_id: _builtins.str
    def __init__(
        self,
        *,
        job_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["job_id", b"job_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSyncJobRequest: _TypeAlias = GetSyncJobRequest  # noqa: Y015

@_typing.final
class ListSyncJobsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STORE_ID_FIELD_NUMBER: _builtins.int
    STATUS_FIELD_NUMBER: _builtins.int
    PAGINATION_FIELD_NUMBER: _builtins.int
    store_id: _builtins.str
    status: Global___SyncJobStatus.ValueType
    @_builtins.property
    def pagination(self) -> _common_pb2.Pagination: ...
    def __init__(
        self,
        *,
        store_id: _builtins.str = ...,
        status: Global___SyncJobStatus.ValueType | None = ...,
        pagination: _common_pb2.Pagination | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_status", b"_status", "pagination", b"pagination", "status", b"status"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_status", b"_status", "pagination", b"pagination", "status", b"status", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__status: _TypeAlias = _typing.Literal["status"]  # noqa: Y015
    _WhichOneofArgType__status: _TypeAlias = _typing.Literal["_status", b"_status"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__status) -> _WhichOneofReturnType__status | None: ...

Global___ListSyncJobsRequest: _TypeAlias = ListSyncJobsRequest  # noqa: Y015

@_typing.final
class ListSyncJobsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JOBS_FIELD_NUMBER: _builtins.int
    PAGE_INFO_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def jobs(self) -> _containers.RepeatedCompositeFieldContainer[Global___SyncJob]: ...
    @_builtins.property
    def page_info(self) -> _common_pb2.PageInfo: ...
    def __init__(
        self,
        *,
        jobs: _abc.Iterable[Global___SyncJob] | None = ...,
        page_info: _common_pb2.PageInfo | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["page_info", b"page_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["jobs", b"jobs", "page_info", b"page_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListSyncJobsResponse: _TypeAlias = ListSyncJobsResponse  # noqa: Y015
