# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from common.v1 import common_pb2 as common_dot_v1_dot_common__pb2
from profile.v1 import profile_pb2 as profile_dot_v1_dot_profile__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in profile/v1/profile_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProfileServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProfile = channel.unary_unary(
                '/profile.v1.ProfileService/GetProfile',
                request_serializer=profile_dot_v1_dot_profile__pb2.GetProfileRequest.SerializeToString,
                response_deserializer=profile_dot_v1_dot_profile__pb2.AudienceProfile.FromString,
                _registered_method=True)
        self.UpdateProfile = channel.unary_unary(
                '/profile.v1.ProfileService/UpdateProfile',
                request_serializer=profile_dot_v1_dot_profile__pb2.UpdateProfileRequest.SerializeToString,
                response_deserializer=profile_dot_v1_dot_profile__pb2.AudienceProfile.FromString,
                _registered_method=True)
        self.TrackEvent = channel.unary_unary(
                '/profile.v1.ProfileService/TrackEvent',
                request_serializer=profile_dot_v1_dot_profile__pb2.TrackEventRequest.SerializeToString,
                response_deserializer=common_dot_v1_dot_common__pb2.Error.FromString,
                _registered_method=True)
        self.GetSegment = channel.unary_unary(
                '/profile.v1.ProfileService/GetSegment',
                request_serializer=profile_dot_v1_dot_profile__pb2.GetSegmentRequest.SerializeToString,
                response_deserializer=profile_dot_v1_dot_profile__pb2.Segment.FromString,
                _registered_method=True)


class ProfileServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetProfile(self, request, context):
        """── Profile ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TrackEvent(self, request, context):
        """── Behavior Tracking ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSegment(self, request, context):
        """── Segmentation ──
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfile,
                    request_deserializer=profile_dot_v1_dot_profile__pb2.GetProfileRequest.FromString,
                    response_serializer=profile_dot_v1_dot_profile__pb2.AudienceProfile.SerializeToString,
            ),
            'UpdateProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProfile,
                    request_deserializer=profile_dot_v1_dot_profile__pb2.UpdateProfileRequest.FromString,
                    response_serializer=profile_dot_v1_dot_profile__pb2.AudienceProfile.SerializeToString,
            ),
            'TrackEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackEvent,
                    request_deserializer=profile_dot_v1_dot_profile__pb2.TrackEventRequest.FromString,
                    response_serializer=common_dot_v1_dot_common__pb2.Error.SerializeToString,
            ),
            'GetSegment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSegment,
                    request_deserializer=profile_dot_v1_dot_profile__pb2.GetSegmentRequest.FromString,
                    response_serializer=profile_dot_v1_dot_profile__pb2.Segment.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'profile.v1.ProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('profile.v1.ProfileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfileService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.v1.ProfileService/GetProfile',
            profile_dot_v1_dot_profile__pb2.GetProfileRequest.SerializeToString,
            profile_dot_v1_dot_profile__pb2.AudienceProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.v1.ProfileService/UpdateProfile',
            profile_dot_v1_dot_profile__pb2.UpdateProfileRequest.SerializeToString,
            profile_dot_v1_dot_profile__pb2.AudienceProfile.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TrackEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.v1.ProfileService/TrackEvent',
            profile_dot_v1_dot_profile__pb2.TrackEventRequest.SerializeToString,
            common_dot_v1_dot_common__pb2.Error.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSegment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/profile.v1.ProfileService/GetSegment',
            profile_dot_v1_dot_profile__pb2.GetSegmentRequest.SerializeToString,
            profile_dot_v1_dot_profile__pb2.Segment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
