"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Profile Service — User Profile, Behavior Tracking, Audience Segmentation"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AudienceProfile(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PROFILE_ID_FIELD_NUMBER: _builtins.int
    PLATFORM_USER_ID_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    NICKNAME_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    VISIT_COUNT_FIELD_NUMBER: _builtins.int
    PURCHASE_COUNT_FIELD_NUMBER: _builtins.int
    TOTAL_SPENT_FEN_FIELD_NUMBER: _builtins.int
    INTEREST_CATEGORIES_FIELD_NUMBER: _builtins.int
    LAST_INTERACTION_TEXT_FIELD_NUMBER: _builtins.int
    LAST_SEEN_AT_FIELD_NUMBER: _builtins.int
    CREATED_AT_FIELD_NUMBER: _builtins.int
    profile_id: _builtins.str
    platform_user_id: _builtins.str
    platform: _builtins.str
    nickname: _builtins.str
    visit_count: _builtins.int
    purchase_count: _builtins.int
    total_spent_fen: _builtins.int
    last_interaction_text: _builtins.str
    last_seen_at: _builtins.int
    created_at: _builtins.int
    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def interest_categories(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        profile_id: _builtins.str = ...,
        platform_user_id: _builtins.str = ...,
        platform: _builtins.str = ...,
        nickname: _builtins.str = ...,
        tags: _abc.Iterable[_builtins.str] | None = ...,
        visit_count: _builtins.int = ...,
        purchase_count: _builtins.int = ...,
        total_spent_fen: _builtins.int = ...,
        interest_categories: _abc.Iterable[_builtins.str] | None = ...,
        last_interaction_text: _builtins.str = ...,
        last_seen_at: _builtins.int = ...,
        created_at: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["created_at", b"created_at", "interest_categories", b"interest_categories", "last_interaction_text", b"last_interaction_text", "last_seen_at", b"last_seen_at", "nickname", b"nickname", "platform", b"platform", "platform_user_id", b"platform_user_id", "profile_id", b"profile_id", "purchase_count", b"purchase_count", "tags", b"tags", "total_spent_fen", b"total_spent_fen", "visit_count", b"visit_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AudienceProfile: _TypeAlias = AudienceProfile  # noqa: Y015

@_typing.final
class Segment(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SEGMENT_ID_FIELD_NUMBER: _builtins.int
    STORE_ID_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    RULE_JSON_FIELD_NUMBER: _builtins.int
    AUDIENCE_SIZE_FIELD_NUMBER: _builtins.int
    segment_id: _builtins.str
    store_id: _builtins.str
    name: _builtins.str
    rule_json: _builtins.str
    audience_size: _builtins.int
    def __init__(
        self,
        *,
        segment_id: _builtins.str = ...,
        store_id: _builtins.str = ...,
        name: _builtins.str = ...,
        rule_json: _builtins.str = ...,
        audience_size: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audience_size", b"audience_size", "name", b"name", "rule_json", b"rule_json", "segment_id", b"segment_id", "store_id", b"store_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Segment: _TypeAlias = Segment  # noqa: Y015

@_typing.final
class GetProfileRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PLATFORM_USER_ID_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    platform_user_id: _builtins.str
    platform: _builtins.str
    def __init__(
        self,
        *,
        platform_user_id: _builtins.str = ...,
        platform: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["platform", b"platform", "platform_user_id", b"platform_user_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetProfileRequest: _TypeAlias = GetProfileRequest  # noqa: Y015

@_typing.final
class UpdateProfileRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PLATFORM_USER_ID_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    NICKNAME_FIELD_NUMBER: _builtins.int
    TAGS_FIELD_NUMBER: _builtins.int
    platform_user_id: _builtins.str
    platform: _builtins.str
    nickname: _builtins.str
    @_builtins.property
    def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        platform_user_id: _builtins.str = ...,
        platform: _builtins.str = ...,
        nickname: _builtins.str | None = ...,
        tags: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["_nickname", b"_nickname", "nickname", b"nickname"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["_nickname", b"_nickname", "nickname", b"nickname", "platform", b"platform", "platform_user_id", b"platform_user_id", "tags", b"tags"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType__nickname: _TypeAlias = _typing.Literal["nickname"]  # noqa: Y015
    _WhichOneofArgType__nickname: _TypeAlias = _typing.Literal["_nickname", b"_nickname"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType__nickname) -> _WhichOneofReturnType__nickname | None: ...

Global___UpdateProfileRequest: _TypeAlias = UpdateProfileRequest  # noqa: Y015

@_typing.final
class TrackEventRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PropertiesEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    PLATFORM_USER_ID_FIELD_NUMBER: _builtins.int
    PLATFORM_FIELD_NUMBER: _builtins.int
    EVENT_TYPE_FIELD_NUMBER: _builtins.int
    LIVE_ROOM_ID_FIELD_NUMBER: _builtins.int
    PROPERTIES_FIELD_NUMBER: _builtins.int
    platform_user_id: _builtins.str
    platform: _builtins.str
    event_type: _builtins.str
    live_room_id: _builtins.str
    @_builtins.property
    def properties(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]: ...
    def __init__(
        self,
        *,
        platform_user_id: _builtins.str = ...,
        platform: _builtins.str = ...,
        event_type: _builtins.str = ...,
        live_room_id: _builtins.str = ...,
        properties: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_type", b"event_type", "live_room_id", b"live_room_id", "platform", b"platform", "platform_user_id", b"platform_user_id", "properties", b"properties"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TrackEventRequest: _TypeAlias = TrackEventRequest  # noqa: Y015

@_typing.final
class GetSegmentRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SEGMENT_ID_FIELD_NUMBER: _builtins.int
    segment_id: _builtins.str
    def __init__(
        self,
        *,
        segment_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["segment_id", b"segment_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___GetSegmentRequest: _TypeAlias = GetSegmentRequest  # noqa: Y015
